/**
 * disease-master-list.ts
 *
 * Collect comprehensive veterinary disease candidates from multiple sources:
 * 1. Merck Veterinary Manual section titles (11,526 sections)
 * 2. Curated veterinary disease taxonomy (organized by specialty)
 * 3. MeSH terms via NCBI E-utilities
 *
 * Output: scripts/disease-candidates.json
 */
import fs from "fs";
import path from "path";

const MERCK_SECTIONS_DIR = "C:/project/merck-sections";
const OUTPUT_FILE = path.join(process.cwd(), "scripts", "disease-candidates.json");

// ─── Merck Section Extraction ─────────────────────────
function extractMerckDiseases(): string[] {
  const indexPath = path.join(MERCK_SECTIONS_DIR, "index.json");
  if (!fs.existsSync(indexPath)) {
    console.warn("Merck sections index not found, skipping");
    return [];
  }

  const index = JSON.parse(fs.readFileSync(indexPath, "utf-8"));
  const diseases: string[] = [];

  // Filter for disease-like section titles
  const skipPatterns = [
    /^(INTRODUCTION|OVERVIEW|TABLE|FIGURE|CHAPTER|INDEX|APPENDIX)/i,
    /^(THE |GENERAL |PRINCIPLES OF |APPROACH TO)/i,
    /\d{3,}/, // Page numbers only
    /^[A-Z\s]{1,5}$/, // Too short (likely chapter codes)
  ];

  for (const [chapterCode, chapterData] of Object.entries(index) as [string, any][]) {
    for (const section of chapterData.sections) {
      const title = section.title.replace(/\s+\d+$/, "").trim(); // Remove trailing page numbers
      if (title.length < 5) continue;
      if (skipPatterns.some(p => p.test(title))) continue;
      if (section.text_length > 200) { // Only sections with meaningful content
        diseases.push(title);
      }
    }
  }

  return [...new Set(diseases)];
}

// ─── Curated Veterinary Disease Taxonomy ──────────────
// Comprehensive list organized by veterinary specialty
// This covers the ~2,500+ diseases we aim to include
function getCuratedDiseases(): Record<string, string[]> {
  return {
    // ═══ CARDIOLOGY / CIRCULATORY ═══
    cardiac: [
      // Congenital heart disease
      "Ventricular Septal Defect", "Atrial Septal Defect", "Patent Ductus Arteriosus",
      "Tetralogy of Fallot", "Pulmonic Stenosis", "Subaortic Stenosis",
      "Aortic Stenosis", "Tricuspid Valve Dysplasia", "Mitral Valve Dysplasia",
      "Persistent Right Aortic Arch", "Cor Triatriatum", "Endocardial Fibroelastosis",
      "Eisenmenger Syndrome", "Double Outlet Right Ventricle",
      // Acquired heart disease
      "Myxomatous Mitral Valve Disease", "Dilated Cardiomyopathy",
      "Hypertrophic Cardiomyopathy", "Restrictive Cardiomyopathy",
      "Arrhythmogenic Right Ventricular Cardiomyopathy",
      "Infective Endocarditis", "Pericardial Effusion", "Cardiac Tamponade",
      "Congestive Heart Failure", "Atrial Fibrillation",
      "Ventricular Tachycardia", "Supraventricular Tachycardia",
      "Sick Sinus Syndrome", "Atrioventricular Block",
      "Third Degree Heart Block", "Bundle Branch Block",
      "Pulmonary Hypertension", "Pulmonary Thromboembolism",
      "Aortic Thromboembolism", "Heartworm Disease",
      "Systemic Hypertension", "Boxer Cardiomyopathy",
      "Doberman Cardiomyopathy", "Cavalier King Charles Spaniel MVD",
      "Myocarditis", "Pericarditis", "Cardiac Hemangiosarcoma",
      "Cardiac Lymphoma", "Chemodectoma",
    ],
    // ═══ HEMATOLOGY ═══
    hematology: [
      "Immune-Mediated Hemolytic Anemia", "Immune-Mediated Thrombocytopenia",
      "Evans Syndrome", "Non-Regenerative Anemia", "Aplastic Anemia",
      "Pure Red Cell Aplasia", "Iron Deficiency Anemia",
      "Hemolytic Anemia", "Methemoglobinemia", "Heinz Body Anemia",
      "Zinc Toxicosis Hemolytic Anemia", "Babesiosis",
      "Disseminated Intravascular Coagulation", "Von Willebrand Disease",
      "Hemophilia A", "Hemophilia B", "Factor VII Deficiency",
      "Thrombocytopenia", "Thrombocytosis", "Neutropenia",
      "Neutrophilia", "Eosinophilia", "Lymphocytosis",
      "Pancytopenia", "Polycythemia", "Polycythemia Vera",
      "Erythrocytosis", "Leukemia", "Acute Lymphoblastic Leukemia",
      "Chronic Lymphocytic Leukemia", "Acute Myeloid Leukemia",
      "Myelodysplastic Syndrome", "Multiple Myeloma",
      "Transfusion Reactions", "Blood Type Incompatibility",
      "Neonatal Isoerythrolysis", "Coagulopathy",
      "Hypercoagulability", "Histiocytic Sarcoma",
      "Hemophagocytic Syndrome", "Systemic Histiocytosis",
    ],
    // ═══ RESPIRATORY ═══
    respiratory: [
      "Brachycephalic Airway Syndrome", "Laryngeal Paralysis",
      "Tracheal Collapse", "Tracheal Hypoplasia",
      "Kennel Cough", "Canine Infectious Respiratory Disease Complex",
      "Feline Upper Respiratory Infection", "Feline Herpesvirus Rhinitis",
      "Feline Calicivirus Infection", "Chronic Rhinitis",
      "Nasal Aspergillosis", "Nasal Foreign Body",
      "Nasal Tumor", "Nasopharyngeal Polyp", "Nasopharyngeal Stenosis",
      "Pneumonia", "Aspiration Pneumonia", "Fungal Pneumonia",
      "Bacterial Pneumonia", "Viral Pneumonia",
      "Eosinophilic Bronchopneumopathy", "Feline Asthma",
      "Chronic Bronchitis", "Bronchiectasis",
      "Pulmonary Edema", "Pulmonary Fibrosis",
      "Pulmonary Contusion", "Pulmonary Abscess",
      "Lung Lobe Torsion", "Primary Lung Tumor",
      "Pulmonary Metastasis", "Pleural Effusion",
      "Chylothorax", "Pyothorax", "Hemothorax",
      "Pneumothorax", "Tension Pneumothorax",
      "Diaphragmatic Hernia", "Peritoneopericardial Diaphragmatic Hernia",
      "Mediastinal Mass", "Thymoma",
      "Acute Respiratory Distress Syndrome",
      "Smoke Inhalation Injury", "Near Drowning",
      "Tracheal Avulsion", "Epiglottic Retroversion",
      "Subglottic Stenosis", "Tracheal Tear",
    ],
    // ═══ GASTROINTESTINAL ═══
    gastrointestinal: [
      "Megaesophagus", "Esophageal Stricture", "Esophageal Foreign Body",
      "Esophagitis", "Hiatal Hernia", "Vascular Ring Anomaly",
      "Gastric Dilatation Volvulus", "Gastric Foreign Body",
      "Gastric Ulcer", "Gastritis", "Chronic Gastritis",
      "Helicobacter Gastritis", "Gastroparesis",
      "Pyloric Stenosis", "Gastric Neoplasia",
      "Intestinal Foreign Body", "Intestinal Intussusception",
      "Intestinal Volvulus", "Mesenteric Torsion",
      "Small Intestinal Bacterial Overgrowth",
      "Inflammatory Bowel Disease", "Lymphocytic Plasmacytic Enteritis",
      "Eosinophilic Enteritis", "Granulomatous Enteritis",
      "Protein Losing Enteropathy", "Intestinal Lymphangiectasia",
      "Chronic Enteropathy", "Food Responsive Enteropathy",
      "Antibiotic Responsive Enteropathy",
      "Colitis", "Histiocytic Ulcerative Colitis",
      "Fiber Responsive Colitis", "Irritable Bowel Syndrome",
      "Constipation", "Megacolon", "Obstipation",
      "Rectal Prolapse", "Perianal Fistula",
      "Anal Sac Disease", "Anal Sac Adenocarcinoma",
      "Intestinal Lymphoma", "Intestinal Adenocarcinoma",
      "Intestinal Leiomyoma", "Intestinal Leiomyosarcoma",
      "Gastrointestinal Stromal Tumor",
      "Pancreatitis", "Acute Pancreatitis", "Chronic Pancreatitis",
      "Exocrine Pancreatic Insufficiency", "Pancreatic Abscess",
      "Pancreatic Neoplasia", "Insulinoma",
      "Parvoviral Enteritis", "Canine Coronavirus Enteritis",
      "Salmonellosis", "Campylobacteriosis",
      "Clostridium Difficile Infection", "Clostridium Perfringens Enterotoxicosis",
      "Tritrichomonas Foetus", "Giardiasis", "Coccidia Infection",
      "Hemorrhagic Gastroenteritis", "Short Bowel Syndrome",
      "Ileus", "Peritonitis", "Bile Peritonitis",
      "Salivary Mucocele", "Sialocele",
      "Oral Melanoma", "Squamous Cell Carcinoma of the Oral Cavity",
      "Oral Fibrosarcoma", "Epulis", "Gingival Hyperplasia",
      "Stomatitis", "Feline Chronic Gingivostomatitis",
    ],
    // ═══ HEPATIC / LIVER ═══
    hepatic: [
      "Chronic Hepatitis", "Acute Hepatic Failure",
      "Hepatic Lipidosis", "Copper Hepatopathy",
      "Cholangitis", "Cholangiohepatitis",
      "Triaditis", "Biliary Obstruction",
      "Gallbladder Mucocele", "Cholelithiasis",
      "Portosystemic Shunt", "Congenital Portosystemic Shunt",
      "Acquired Portosystemic Shunt",
      "Hepatic Encephalopathy", "Hepatic Fibrosis",
      "Cirrhosis", "Hepatic Abscess",
      "Hepatocellular Carcinoma", "Hepatic Lymphoma",
      "Biliary Carcinoma", "Cholecystitis",
      "Vacuolar Hepatopathy", "Drug-Induced Hepatotoxicity",
      "Lobular Dissecting Hepatitis",
      "Hepatocutaneous Syndrome", "Nodular Hyperplasia of the Liver",
      "Hepatic Amyloidosis",
    ],
    // ═══ URINARY / RENAL ═══
    urinary: [
      "Chronic Kidney Disease", "Acute Kidney Injury",
      "Glomerulonephritis", "Protein Losing Nephropathy",
      "Amyloidosis Renal", "Polycystic Kidney Disease",
      "Renal Dysplasia", "Pyelonephritis",
      "Urolithiasis", "Calcium Oxalate Urolithiasis",
      "Struvite Urolithiasis", "Urate Urolithiasis",
      "Cystine Urolithiasis", "Silica Urolithiasis",
      "Feline Lower Urinary Tract Disease", "Feline Idiopathic Cystitis",
      "Urethral Obstruction", "Urinary Tract Infection",
      "Ectopic Ureter", "Urinary Incontinence",
      "Urethral Prolapse", "Urethral Stricture",
      "Bladder Neoplasia", "Transitional Cell Carcinoma",
      "Renal Lymphoma", "Renal Cell Carcinoma",
      "Nephroblastoma", "Hydronephrosis",
      "Renal Tubular Acidosis", "Fanconi Syndrome",
      "Juvenile Nephropathy", "Familial Nephropathy",
      "Nephrotic Syndrome", "Peritoneal Dialysis Complications",
    ],
    // ═══ ENDOCRINE ═══
    endocrine: [
      "Diabetes Mellitus", "Diabetic Ketoacidosis",
      "Diabetic Neuropathy", "Somogyi Effect",
      "Hypoglycemia", "Insulinoma",
      "Hyperadrenocorticism", "Pituitary Dependent Hyperadrenocorticism",
      "Adrenal Dependent Hyperadrenocorticism", "Iatrogenic Hyperadrenocorticism",
      "Hypoadrenocorticism", "Atypical Hypoadrenocorticism",
      "Hypothyroidism", "Congenital Hypothyroidism",
      "Hyperthyroidism", "Thyroid Carcinoma",
      "Hyperparathyroidism", "Primary Hyperparathyroidism",
      "Secondary Renal Hyperparathyroidism", "Nutritional Hyperparathyroidism",
      "Hypoparathyroidism",
      "Pheochromocytoma", "Aldosterone Secreting Tumor",
      "Adrenocortical Carcinoma",
      "Acromegaly", "Pituitary Dwarfism", "Diabetes Insipidus",
      "Central Diabetes Insipidus", "Nephrogenic Diabetes Insipidus",
      "Syndrome of Inappropriate Antidiuretic Hormone",
      "Hyperaldosteronism", "Ferret Adrenal Disease",
    ],
    // ═══ NEUROLOGY ═══
    neurology: [
      "Intervertebral Disc Disease", "Cervical Disc Disease",
      "Thoracolumbar Disc Disease", "Fibrocartilaginous Embolism",
      "Degenerative Myelopathy", "Cervical Spondylomyelopathy",
      "Atlantoaxial Instability", "Cauda Equina Syndrome",
      "Lumbosacral Stenosis", "Syringomyelia",
      "Chiari-Like Malformation", "Spinal Cord Tumor",
      "Meningioma", "Glioma", "Choroid Plexus Tumor",
      "Brain Tumor", "Pituitary Macroadenoma",
      "Idiopathic Epilepsy", "Structural Epilepsy",
      "Status Epilepticus", "Cluster Seizures",
      "Meningitis", "Meningoencephalitis of Unknown Origin",
      "Granulomatous Meningoencephalitis",
      "Necrotizing Encephalitis", "Necrotizing Leukoencephalitis",
      "Steroid Responsive Meningitis Arteritis",
      "Canine Distemper Encephalitis", "Feline Infectious Peritonitis Neurologic",
      "Toxoplasma Encephalitis", "Neosporosis",
      "Rabies", "Vestibular Disease", "Peripheral Vestibular Disease",
      "Central Vestibular Disease", "Idiopathic Vestibular Syndrome",
      "Facial Nerve Paralysis", "Trigeminal Neuritis",
      "Horner Syndrome", "Brachial Plexus Avulsion",
      "Polyradiculoneuritis", "Coonhound Paralysis",
      "Myasthenia Gravis", "Acquired Myasthenia Gravis",
      "Congenital Myasthenia Gravis",
      "Tetanus", "Botulism",
      "Cognitive Dysfunction Syndrome",
      "Hydrocephalus", "Cerebellar Hypoplasia",
      "Cerebellar Abiotrophy", "Lissencephaly",
      "Spinal Dysraphism", "Hemivertebra",
      "Polymyositis", "Masticatory Muscle Myositis",
      "Extraocular Myositis", "Muscular Dystrophy",
      "Narcolepsy", "Scotty Cramp",
      "Dancing Doberman Disease", "Sensory Neuropathy",
      "Metabolic Encephalopathy", "Hepatic Encephalopathy Neurologic",
      "Uremic Encephalopathy",
    ],
    // ═══ OPHTHALMOLOGY ═══
    ophthalmology: [
      "Corneal Ulcer", "Indolent Ulcer", "Melting Ulcer",
      "Corneal Sequestrum", "Keratoconjunctivitis Sicca",
      "Conjunctivitis", "Allergic Conjunctivitis",
      "Cherry Eye", "Entropion", "Ectropion",
      "Distichiasis", "Ectopic Cilia", "Trichiasis",
      "Cataracts", "Lens Luxation", "Nuclear Sclerosis",
      "Glaucoma", "Primary Glaucoma", "Secondary Glaucoma",
      "Anterior Uveitis", "Posterior Uveitis", "Panuveitis",
      "Lens Induced Uveitis", "Traumatic Uveitis",
      "Progressive Retinal Atrophy", "Sudden Acquired Retinal Degeneration",
      "Retinal Detachment", "Retinal Hemorrhage",
      "Collie Eye Anomaly", "Persistent Pupillary Membranes",
      "Persistent Hyperplastic Primary Vitreous",
      "Iris Melanosis", "Iris Melanoma", "Uveal Melanoma",
      "Orbital Neoplasia", "Retrobulbar Abscess",
      "Proptosis", "Hyphema", "Corneal Dystrophy",
      "Corneal Degeneration", "Lipid Keratopathy",
      "Pannus", "Chronic Superficial Keratitis",
      "Feline Eosinophilic Keratitis", "Symblepharon",
      "Blepharitis", "Meibomian Gland Dysfunction",
      "Epiphora", "Nasolacrimal Duct Obstruction",
      "Canine Multifocal Retinopathy", "Optic Neuritis",
      "Phacoclastic Uveitis",
    ],
    // ═══ EAR ═══
    ear: [
      "Otitis Externa", "Otitis Media", "Otitis Interna",
      "Aural Hematoma", "Ear Mites", "Nasopharyngeal Polyp",
      "Deafness", "Congenital Deafness",
      "Ear Canal Tumor", "Ceruminous Gland Adenocarcinoma",
      "Total Ear Canal Ablation", "Lateral Ear Resection",
      "Ear Margin Dermatosis", "Pinnal Vasculitis",
    ],
    // ═══ DERMATOLOGY ═══
    dermatology: [
      "Atopic Dermatitis", "Food Allergy Dermatitis",
      "Flea Allergy Dermatitis", "Contact Dermatitis",
      "Pyoderma", "Superficial Pyoderma", "Deep Pyoderma",
      "Methicillin Resistant Staphylococcus", "Skin Fold Dermatitis",
      "Demodicosis", "Generalized Demodicosis", "Localized Demodicosis",
      "Sarcoptic Mange", "Notoedric Mange",
      "Cheyletiellosis", "Dermatophytosis", "Malassezia Dermatitis",
      "Hot Spot", "Acral Lick Dermatitis",
      "Pemphigus Foliaceus", "Pemphigus Vulgaris",
      "Bullous Pemphigoid", "Discoid Lupus Erythematosus",
      "Systemic Lupus Erythematosus", "Vasculitis",
      "Erythema Multiforme", "Toxic Epidermal Necrolysis",
      "Drug Eruption", "Sebaceous Adenitis",
      "Alopecia X", "Pattern Baldness",
      "Color Dilution Alopecia", "Seasonal Flank Alopecia",
      "Dermoid Sinus", "Calcinosis Cutis",
      "Cutaneous Lymphoma", "Mast Cell Tumor",
      "Soft Tissue Sarcoma", "Fibrosarcoma",
      "Squamous Cell Carcinoma Cutaneous", "Melanoma Cutaneous",
      "Histiocytoma", "Lipoma", "Liposarcoma",
      "Sebaceous Gland Tumor", "Perianal Gland Tumor",
      "Trichoepithelioma", "Pilomatricoma",
      "Basal Cell Tumor", "Hemangiopericytoma",
      "Subcutaneous Hemangiosarcoma",
      "Acanthomatous Ameloblastoma",
      "Digital Squamous Cell Carcinoma",
      "Nail Bed Tumor", "Subungual Melanoma",
      "Panniculitis", "Sterile Nodular Panniculitis",
      "Juvenile Cellulitis", "Canine Acne",
      "Zinc Responsive Dermatosis", "Vitamin A Responsive Dermatosis",
      "Hypothyroid Dermatosis", "Hyperadrenocorticism Dermatosis",
      "Shar-Pei Fever", "Shar-Pei Amyloidosis",
      "Callus Dermatitis", "Pressure Sore",
      "Fly Strike Dermatitis",
    ],
    // ═══ ORTHOPEDIC / MUSCULOSKELETAL ═══
    orthopedic: [
      "Cranial Cruciate Ligament Rupture", "Medial Patellar Luxation",
      "Lateral Patellar Luxation", "Hip Dysplasia",
      "Elbow Dysplasia", "Fragmented Coronoid Process",
      "Ununited Anconeal Process", "Osteochondritis Dissecans",
      "Legg Calve Perthes Disease", "Aseptic Necrosis Femoral Head",
      "Fracture Management", "Radius Ulna Fracture",
      "Femoral Fracture", "Tibial Fracture",
      "Humeral Fracture", "Pelvic Fracture",
      "Spinal Fracture", "Mandibular Fracture",
      "Growth Plate Fracture", "Pathologic Fracture",
      "Angular Limb Deformity", "Premature Physeal Closure",
      "Panosteitis", "Hypertrophic Osteodystrophy",
      "Hypertrophic Osteopathy",
      "Osteosarcoma", "Chondrosarcoma", "Synovial Sarcoma",
      "Multilobular Osteochondrosarcoma",
      "Osteomyelitis", "Septic Arthritis",
      "Immune-Mediated Polyarthritis", "Rheumatoid Arthritis",
      "Polyarthritis", "Osteoarthritis",
      "Muscle Strain", "Tendon Injury",
      "Biceps Tendinopathy", "Supraspinatus Tendinopathy",
      "Infraspinatus Contracture", "Gracilis Contracture",
      "Fibrotic Myopathy", "Achilles Tendon Rupture",
      "Carpal Hyperextension", "Tarsal Instability",
      "Shoulder Luxation", "Hip Luxation",
      "Temporomandibular Joint Luxation",
      "Coxofemoral Luxation",
      "Scottish Fold Osteochondrodysplasia",
      "Mucopolysaccharidosis", "Glycogen Storage Disease",
    ],
    // ═══ DENTAL ═══
    dental: [
      "Periodontal Disease", "Tooth Resorption",
      "Feline Odontoclastic Resorptive Lesion",
      "Tooth Fracture", "Dental Abscess",
      "Malocclusion", "Mandibular Prognathism",
      "Maxillary Brachygnathism", "Deciduous Tooth Retention",
      "Supernumerary Teeth", "Missing Teeth",
      "Enamel Hypoplasia", "Tooth Discoloration",
      "Mandibular Osteomyelitis", "Oronasal Fistula",
      "Jaw Fracture Dental", "Dentigerous Cyst",
      "Ameloblastoma", "Oral Papilloma",
    ],
    // ═══ ONCOLOGY ═══
    oncology: [
      "Lymphoma", "Multicentric Lymphoma", "Mediastinal Lymphoma",
      "Alimentary Lymphoma", "Cutaneous Lymphoma",
      "Hepatosplenic Lymphoma", "Large Granular Lymphocyte Lymphoma",
      "Mast Cell Tumor", "Hemangiosarcoma", "Splenic Hemangiosarcoma",
      "Osteosarcoma", "Soft Tissue Sarcoma",
      "Fibrosarcoma", "Injection Site Sarcoma",
      "Melanoma", "Oral Melanoma",
      "Squamous Cell Carcinoma", "Nasal Tumor",
      "Thyroid Carcinoma", "Mammary Tumor",
      "Mammary Adenocarcinoma", "Ovarian Tumor",
      "Testicular Tumor", "Sertoli Cell Tumor",
      "Seminoma", "Leydig Cell Tumor",
      "Prostate Carcinoma", "Prostatic Adenocarcinoma",
      "Transitional Cell Carcinoma", "Bladder Tumor",
      "Brain Tumor Oncology", "Meningioma Oncology",
      "Pituitary Tumor", "Adrenal Tumor",
      "Hepatocellular Carcinoma Oncology", "Bile Duct Carcinoma",
      "Pancreatic Carcinoma", "Anal Sac Adenocarcinoma Oncology",
      "Apocrine Gland Carcinoma", "Perianal Adenoma",
      "Lung Carcinoma", "Pulmonary Adenocarcinoma",
      "Cardiac Tumor", "Chemodectoma Oncology",
      "Thymoma Oncology", "Ectopic Thyroid Carcinoma",
      "Multiple Endocrine Neoplasia",
      "Paraneoplastic Syndrome", "Hypercalcemia of Malignancy",
      "Cancer Associated Cachexia",
      "Chondrosarcoma Oncology", "Osteochondroma",
      "Vaccine Associated Sarcoma",
      "Feline Mammary Carcinoma",
      "Canine Histiocytic Sarcoma",
      "Hemangiopericytoma Oncology", "Liposarcoma Oncology",
      "Peripheral Nerve Sheath Tumor",
      "Gastrointestinal Stromal Tumor Oncology",
      "Intestinal Adenocarcinoma Oncology",
      "Splenic Tumor", "Splenic Mass",
    ],
    // ═══ INFECTIOUS DISEASE ═══
    infectious: [
      // Viral
      "Canine Parvovirus", "Canine Distemper",
      "Canine Infectious Hepatitis", "Canine Coronavirus",
      "Canine Influenza", "Canine Herpesvirus",
      "Canine Papillomatosis",
      "Feline Panleukopenia", "Feline Herpesvirus",
      "Feline Calicivirus", "Feline Leukemia Virus",
      "Feline Immunodeficiency Virus", "Feline Infectious Peritonitis",
      "Feline Coronavirus",
      "Rabies",
      // Bacterial
      "Leptospirosis", "Brucellosis", "Bartonellosis",
      "Borreliosis", "Lyme Disease",
      "Ehrlichiosis", "Anaplasmosis",
      "Rocky Mountain Spotted Fever", "Rickettsiosis",
      "Nocardiosis", "Actinomycosis",
      "Mycobacterial Infection", "Tularemia",
      "Plague", "Salmonellosis Infectious",
      "Campylobacteriosis Infectious",
      "Listeriosis", "Leptospirosis Systemic",
      "Bordetella Bronchiseptica", "Tetanus Infectious",
      "Clostridial Infection",
      "Streptococcal Infection", "Staphylococcal Infection",
      "Pseudomonas Infection", "E Coli Infection",
      // Fungal
      "Blastomycosis", "Histoplasmosis",
      "Coccidioidomycosis", "Cryptococcosis",
      "Aspergillosis", "Sporotrichosis",
      "Dermatophytosis Infectious", "Pythiosis",
      "Lagenidiosis", "Protothecosis",
      // Protozoal
      "Babesiosis", "Cytauxzoonosis",
      "Hepatozoonosis", "Leishmaniasis",
      "Toxoplasmosis", "Neosporosis Infectious",
      "Giardiasis Infectious", "Coccidiosis",
      "Trypanosomiasis", "Tritrichomonas",
      // Parasitic
      "Heartworm Disease Infectious", "Toxocariasis",
      "Hookworm Infection", "Whipworm Infection",
      "Tapeworm Infection", "Lungworm Infection",
      "Angiostrongylosis", "Dirofilariasis",
      "Strongyloides", "Filaroides",
      "Cuterebra", "Myiasis",
      "Demodex Infectious", "Sarcoptes Infectious",
    ],
    // ═══ TOXICOLOGY ═══
    toxicology: [
      "Chocolate Toxicosis", "Xylitol Toxicosis",
      "Grape and Raisin Toxicosis", "Onion and Garlic Toxicosis",
      "Macadamia Nut Toxicosis", "Avocado Toxicosis",
      "Alcohol Toxicosis", "Caffeine Toxicosis",
      "Ethylene Glycol Toxicosis", "Antifreeze Poisoning",
      "Anticoagulant Rodenticide Toxicosis", "Bromethalin Toxicosis",
      "Cholecalciferol Rodenticide Toxicosis", "Zinc Phosphide Toxicosis",
      "Strychnine Toxicosis",
      "Organophosphate Toxicosis", "Pyrethrin Pyrethroid Toxicosis",
      "Permethrin Toxicosis in Cats", "Ivermectin Toxicosis",
      "Metaldehyde Toxicosis", "Snail Bait Toxicosis",
      "Acetaminophen Toxicosis", "NSAID Toxicosis",
      "Ibuprofen Toxicosis", "Naproxen Toxicosis",
      "Aspirin Toxicosis", "Corticosteroid Overdose",
      "Lead Toxicosis", "Zinc Toxicosis",
      "Copper Toxicosis", "Iron Toxicosis",
      "Arsenic Toxicosis", "Mercury Toxicosis",
      "Lily Toxicosis", "Sago Palm Toxicosis",
      "Oleander Toxicosis", "Autumn Crocus Toxicosis",
      "Castor Bean Toxicosis", "Marijuana Toxicosis",
      "Cannabis Toxicosis", "Mushroom Toxicosis",
      "Blue-Green Algae Toxicosis", "Cyanobacteria Toxicosis",
      "Toad Toxicosis", "Bee and Wasp Sting Toxicosis",
      "Snake Envenomation", "Spider Envenomation",
      "Scorpion Envenomation",
      "Salt Toxicosis", "Water Intoxication",
      "Fluoride Toxicosis",
      "Aflatoxicosis", "Mycotoxicosis",
      "5-Fluorouracil Toxicosis", "Phenobarbital Toxicosis",
      "Benzodiazepine Toxicosis",
      "Sympathomimetic Toxicosis", "Amphetamine Toxicosis",
      "SSRI Toxicosis", "Tricyclic Antidepressant Toxicosis",
    ],
    // ═══ IMMUNOLOGY ═══
    immunology: [
      "Immune-Mediated Hemolytic Anemia Immunology",
      "Immune-Mediated Thrombocytopenia Immunology",
      "Systemic Lupus Erythematosus Immunology",
      "Pemphigus Complex",
      "Discoid Lupus Erythematosus Immunology",
      "Rheumatoid Arthritis Immunology",
      "Immune-Mediated Polyarthritis Immunology",
      "Vasculitis Immunology", "Polyarteritis Nodosa",
      "Anaphylaxis", "Angioedema", "Urticaria",
      "Drug Hypersensitivity", "Vaccine Reactions",
      "Serum Sickness", "Type I Hypersensitivity",
      "Type II Hypersensitivity", "Type III Hypersensitivity",
      "Type IV Hypersensitivity",
      "Immunodeficiency Syndromes",
      "Combined Immunodeficiency",
      "Selective IgA Deficiency",
      "Complement Deficiency",
      "Cyclic Hematopoiesis",
    ],
    // ═══ REPRODUCTIVE ═══
    reproductive: [
      "Pyometra", "Cystic Endometrial Hyperplasia",
      "Vaginitis", "Metritis",
      "Dystocia", "Uterine Inertia",
      "Eclampsia", "Pregnancy Toxemia",
      "Mastitis", "Agalactia",
      "Cryptorchidism", "Testicular Tumor",
      "Prostatic Disease", "Benign Prostatic Hyperplasia",
      "Prostatitis", "Prostatic Abscess",
      "Prostatic Cyst", "Prostatic Carcinoma",
      "Mammary Hyperplasia", "Mammary Fibroepithelial Hyperplasia",
      "False Pregnancy", "Pseudopregnancy",
      "Ovarian Remnant Syndrome", "Ovarian Cyst",
      "Infertility Female", "Infertility Male",
      "Breeding Management", "Artificial Insemination Complications",
      "Neonatal Mortality", "Fading Puppy Syndrome",
      "Fading Kitten Syndrome",
      "Canine Transmissible Venereal Tumor",
      "Phimosis", "Paraphimosis",
      "Uterine Prolapse", "Vaginal Prolapse",
      "Penile Prolapse", "Priapism",
      "Subinvolution of Placental Sites",
      "Perineal Hernia",
    ],
    // ═══ EMERGENCY / CRITICAL CARE ═══
    emergency: [
      "Gastric Dilatation Volvulus Emergency",
      "Heatstroke", "Hypothermia",
      "Drowning", "Smoke Inhalation",
      "Electric Shock", "Lightning Strike",
      "Burn Injury", "Chemical Burns",
      "Traumatic Brain Injury", "Spinal Cord Trauma",
      "Thoracic Trauma", "Abdominal Trauma",
      "Hemorrhagic Shock", "Hypovolemic Shock",
      "Distributive Shock", "Cardiogenic Shock",
      "Obstructive Shock", "Septic Shock",
      "Systemic Inflammatory Response Syndrome",
      "Multiple Organ Dysfunction Syndrome",
      "Cardiac Arrest", "Cardiopulmonary Resuscitation",
      "Airway Obstruction", "Choking",
      "Flail Chest", "Rib Fracture",
      "Urethral Obstruction Emergency",
      "Splenic Torsion", "Mesenteric Volvulus",
      "Acute Abdomen", "Hemoabdomen",
      "Uroabdomen", "Pneumoperitoneum",
      "High Rise Syndrome", "Vehicular Trauma",
      "Dog Bite Wound", "Cat Bite Wound",
      "Gunshot Wound", "Penetrating Wound",
      "Degloving Injury", "Wound Management",
      "Massive Transfusion", "Transfusion Medicine",
      "Acute Pain Management", "Triage and Stabilization",
      "Oxygen Therapy", "Mechanical Ventilation",
    ],
    // ═══ METABOLIC / NUTRITIONAL ═══
    metabolic: [
      "Obesity", "Cachexia",
      "Protein-Calorie Malnutrition",
      "Hypokalemia", "Hyperkalemia",
      "Hyponatremia", "Hypernatremia",
      "Hypocalcemia", "Hypercalcemia",
      "Hypomagnesemia", "Hypermagnesemia",
      "Hypophosphatemia", "Hyperphosphatemia",
      "Metabolic Acidosis", "Metabolic Alkalosis",
      "Respiratory Acidosis", "Respiratory Alkalosis",
      "Dehydration", "Fluid Overload",
      "Lactic Acidosis",
      "Hepatic Lipidosis Metabolic",
      "Feline Hepatic Lipidosis",
      "Taurine Deficiency", "Thiamine Deficiency",
      "Vitamin A Deficiency", "Vitamin A Toxicosis",
      "Vitamin D Deficiency", "Vitamin D Toxicosis",
      "Vitamin E Deficiency", "Vitamin K Deficiency",
      "Biotin Deficiency", "Zinc Deficiency",
      "Iron Deficiency", "Copper Deficiency",
      "Iodine Deficiency", "Selenium Deficiency",
      "Guinea Pig Scurvy", "Vitamin C Deficiency",
      "Diabetes Mellitus Metabolic",
      "Hyperlipidemia", "Hyperlipoproteinemia",
      "Amyloidosis", "Lysosomal Storage Disease",
      "Mucopolysaccharidosis Metabolic",
      "Glycogen Storage Disease Metabolic",
    ],
    // ═══ BEHAVIORAL ═══
    behavioral: [
      "Separation Anxiety", "Noise Phobia",
      "Storm Phobia", "Generalized Anxiety Disorder",
      "Compulsive Disorder", "Cognitive Dysfunction Syndrome Behavioral",
      "Aggression Dog", "Fear Aggression",
      "Territorial Aggression", "Redirected Aggression",
      "Predatory Behavior", "Resource Guarding",
      "Inter-Dog Aggression", "Inter-Cat Aggression",
      "Feline Aggression", "Pica",
      "Coprophagia", "Excessive Vocalization",
      "House Soiling", "Urine Marking",
      "Inappropriate Elimination", "Feline House Soiling",
      "Psychogenic Alopecia", "Acral Lick Dermatitis Behavioral",
      "Tail Chasing", "Fly Biting",
      "Canine Dysfunctional Behavior", "Feline Hyperesthesia Syndrome",
    ],
    // ═══ EXOTIC - RABBIT ═══
    rabbit: [
      "Rabbit GI Stasis", "Rabbit Dental Disease",
      "Rabbit Uterine Adenocarcinoma", "Rabbit VHD",
      "Rabbit Myxomatosis", "Rabbit Pasteurellosis",
      "Rabbit Encephalitozoonosis", "Rabbit Coccidiosis",
      "Rabbit Syphilis", "Rabbit Pododermatitis",
      "Rabbit Head Tilt", "Rabbit Ear Mites",
      "Rabbit Flystrike", "Rabbit Myiasis",
      "Rabbit Spinal Fracture", "Rabbit Obesity",
      "Rabbit Urolithiasis", "Rabbit Thymoma",
      "Rabbit Dental Abscess", "Rabbit Cheek Teeth Malocclusion",
      "Rabbit Phacoclastic Uveitis", "Rabbit Otitis",
      "Rabbit Respiratory Infection", "Rabbit Dermatophytosis",
      "Rabbit Pododermatitis Bumblefoot", "Rabbit Hepatic Coccidiosis",
      "Rabbit Intestinal Coccidiosis", "Rabbit Cecal Dysbiosis",
      "Rabbit Heat Stress", "Rabbit Pregnancy Toxemia",
      "Rabbit Tyzzer Disease", "Rabbit Mucoid Enteropathy",
      "Rabbit Hairball Obstruction", "Rabbit Pinworm",
      "Rabbit Red Urine", "Rabbit Hypovitaminosis D",
      "Rabbit Atherosclerosis", "Rabbit Lymphoma",
      "Rabbit Mammary Gland Tumor", "Rabbit Cutaneous Mass",
      "Rabbit Abscess", "Rabbit Mandibular Abscess",
      "Rabbit Corneal Ulcer", "Rabbit Glaucoma",
      "Rabbit Dacryocystitis", "Rabbit Gastric Dilation",
      "Rabbit Megacolon", "Rabbit Congenital Defects",
      "Rabbit Seizure", "Rabbit Posterior Paralysis",
      "Rabbit Antibiotic Toxicity",
      "Rabbit Ovarian Cyst", "Rabbit Orchitis",
      "Rabbit Fur Mites", "Rabbit Treponematosis",
      "Rabbit Viral Hemorrhagic Disease",
      "Rabbit Calicivirus", "Rabbit Herpesvirus",
    ],
    // ═══ EXOTIC - GUINEA PIG ═══
    guinea_pig: [
      "Guinea Pig Scurvy", "Guinea Pig Bumblefoot",
      "Guinea Pig Dental Disease", "Guinea Pig Malocclusion",
      "Guinea Pig Ovarian Cyst", "Guinea Pig Pneumonia",
      "Guinea Pig Pregnancy Toxemia", "Guinea Pig Urolithiasis",
      "Guinea Pig Barbering", "Guinea Pig Dermatophytosis",
      "Guinea Pig Sarcoptic Mange", "Guinea Pig Cervical Lymphadenitis",
      "Guinea Pig GI Stasis", "Guinea Pig Antibiotic Toxicity",
      "Guinea Pig Pododermatitis", "Guinea Pig Cystitis",
      "Guinea Pig Dystocia", "Guinea Pig Bloat",
      "Guinea Pig Heatstroke", "Guinea Pig Diabetes",
      "Guinea Pig Trichofolliculoma", "Guinea Pig Lymphoma",
      "Guinea Pig Mammary Tumor", "Guinea Pig Sebaceous Cyst",
      "Guinea Pig Lice Infestation", "Guinea Pig Bordetella",
      "Guinea Pig Streptococcal Infection",
      "Guinea Pig Vitamin C Deficiency Detailed",
      "Guinea Pig Adipocyte Lipoma",
      "Guinea Pig Conjunctivitis", "Guinea Pig Corneal Ulcer",
      "Guinea Pig Heart Disease", "Guinea Pig Renal Disease",
      "Guinea Pig Cecal Impaction",
      "Guinea Pig Alopecia", "Guinea Pig Satin Syndrome",
    ],
    // ═══ EXOTIC - HAMSTER ═══
    hamster: [
      "Hamster Wet Tail", "Hamster Cheek Pouch Impaction",
      "Hamster Diabetes", "Hamster Hibernation",
      "Hamster Demodicosis", "Hamster Lymphoma",
      "Hamster Dental Overgrowth", "Hamster Amyloidosis",
      "Hamster Congestive Heart Failure",
      "Hamster Skin Tumor", "Hamster Adrenal Tumor",
      "Hamster Polycystic Disease", "Hamster Pyometra",
      "Hamster Cushing Disease",
      "Hamster Bar Rub Alopecia", "Hamster Cage Paralysis",
      "Hamster Intussusception",
      "Hamster Atrial Thrombosis", "Hamster Pododermatitis",
      "Hamster Campylobacteriosis",
      "Hamster Respiratory Infection",
      "Hamster Tyzzer Disease",
      "Hamster Dermatophytosis",
      "Hamster Eye Proptosis",
    ],
    // ═══ EXOTIC - FERRET ═══
    ferret: [
      "Ferret Adrenal Disease", "Ferret Insulinoma",
      "Ferret Lymphoma", "Ferret Aplastic Anemia",
      "Ferret Distemper", "Ferret Influenza",
      "Ferret Epizootic Catarrhal Enteritis",
      "Ferret GI Foreign Body", "Ferret Helicobacter Gastritis",
      "Ferret Cardiomyopathy", "Ferret Heartworm",
      "Ferret Splenomegaly", "Ferret Hyperestrogenism",
      "Ferret Dental Disease", "Ferret Skin Tumor",
      "Ferret Mast Cell Tumor", "Ferret Chordoma",
      "Ferret Aleutian Disease", "Ferret Proliferative Bowel Disease",
      "Ferret Megaesophagus", "Ferret Renal Cyst",
      "Ferret Urolithiasis",
      "Ferret Coronavirus",
      "Ferret Systemic Coronavirus",
      "Ferret Ear Mites", "Ferret Dermatophytosis",
      "Ferret Seasonal Alopecia",
      "Ferret Pneumonia", "Ferret Cryptosporidiosis",
    ],
    // ═══ EXOTIC - CHINCHILLA ═══
    chinchilla: [
      "Chinchilla Dental Disease", "Chinchilla GI Stasis",
      "Chinchilla Fur Ring", "Chinchilla Heatstroke",
      "Chinchilla Dermatophytosis", "Chinchilla Fur Slip",
      "Chinchilla Malocclusion", "Chinchilla Bloat",
      "Chinchilla Constipation", "Chinchilla Diarrhea",
      "Chinchilla Pneumonia", "Chinchilla Otitis Media",
      "Chinchilla Conjunctivitis", "Chinchilla Diabetes",
      "Chinchilla Cardiomyopathy", "Chinchilla Listeriosis",
      "Chinchilla Penile Paraphimosis", "Chinchilla Rectal Prolapse",
      "Chinchilla Seizure", "Chinchilla Vitamin Deficiency",
    ],
    // ═══ EXOTIC - RAT ═══
    rat: [
      "Rat Mycoplasma Respiratory Disease",
      "Rat Mammary Tumor", "Rat Pituitary Adenoma",
      "Rat Tail Degloving", "Rat Ulcerative Dermatitis",
      "Rat Ringtail", "Rat Bumblefoot",
      "Rat Chromodacryorrhea", "Rat Sialodacryoadenitis",
      "Rat Pneumonia", "Rat Barbering",
      "Rat Renal Disease", "Rat Heart Failure",
      "Rat Zymbal Gland Tumor", "Rat Fibrosarcoma",
      "Rat Malocclusion", "Rat Mites",
      "Rat Seizure", "Rat Stroke",
      "Rat Hind Limb Paralysis",
    ],
    // ═══ EXOTIC - BIRD / AVIAN ═══
    avian: [
      "Avian Psittacosis", "Avian Aspergillosis",
      "Avian Proventricular Dilatation Disease",
      "Avian Polyomavirus", "Avian Bornavirus",
      "Psittacine Beak and Feather Disease",
      "Avian Pox", "Avian Candidiasis",
      "Avian Megabacteriosis", "Avian Gout",
      "Avian Egg Binding", "Avian Egg Peritonitis",
      "Avian Crop Stasis", "Avian Crop Burn",
      "Avian Feather Picking", "Avian Self Mutilation",
      "Avian Heavy Metal Toxicosis", "Avian Teflon Toxicosis",
      "Avian Bumblefoot", "Avian Liver Disease",
      "Avian Renal Disease", "Avian Atherosclerosis",
      "Avian Conure Bleeding Syndrome",
      "Avian Cloacal Prolapse", "Avian Obesity",
      "Avian Hypovitaminosis A",
    ],
    // ═══ BREED-SPECIFIC ═══
    breed_specific: [
      "Cavalier King Charles Spaniel Mitral Valve Disease",
      "Cavalier King Charles Spaniel Syringomyelia",
      "Boxer Cardiomyopathy", "Boxer Mast Cell Tumor",
      "Doberman Dilated Cardiomyopathy",
      "German Shepherd Degenerative Myelopathy",
      "German Shepherd Perianal Fistula",
      "Golden Retriever Hemangiosarcoma",
      "Golden Retriever Lymphoma Breed",
      "Labrador Retriever Obesity", "Labrador Exercise Induced Collapse",
      "Dalmatian Hyperuricosuria", "Dalmatian Deafness",
      "Shar-Pei Amyloidosis Breed", "Shar-Pei Fever Breed",
      "Scottish Fold Osteochondrodysplasia Breed",
      "Bulldog Brachycephalic Syndrome",
      "French Bulldog Hemivertebra",
      "French Bulldog IVDD",
      "Cocker Spaniel Immune Mediated Hemolytic Anemia",
      "Cocker Spaniel Ear Disease",
      "West Highland White Terrier Pulmonary Fibrosis",
      "Westie Atopic Dermatitis",
      "Miniature Schnauzer Hyperlipidemia",
      "Miniature Schnauzer Pancreatitis",
      "Bernese Mountain Dog Histiocytic Sarcoma",
      "Great Dane GDV Predisposition",
      "Great Dane Wobbler Syndrome",
      "Rottweiler Osteosarcoma",
      "Irish Setter Gluten Sensitive Enteropathy",
      "English Springer Spaniel Rage Syndrome",
      "Shiba Inu Glaucoma",
      "Persian Cat PKD",
      "Persian Cat Brachycephalic Syndrome",
      "Siamese Cat Amyloidosis",
      "Siamese Cat Megaesophagus",
      "Maine Coon Hypertrophic Cardiomyopathy",
      "Ragdoll Hypertrophic Cardiomyopathy",
      "Bengal Cat PK Deficiency",
      "Abyssinian Cat Renal Amyloidosis",
      "Burmese Cat Diabetes",
      "Burmese Cat Hypokalemic Polymyopathy",
    ],
    // ═══ CONGENITAL / GENETIC ═══
    congenital: [
      "Patent Ductus Arteriosus Congenital",
      "Persistent Right Aortic Arch Congenital",
      "Cleft Palate", "Pectus Excavatum",
      "Portosystemic Shunt Congenital",
      "Ectopic Ureter Congenital",
      "Hydrocephalus Congenital", "Cerebellar Hypoplasia Congenital",
      "Spina Bifida", "Meningomyelocele",
      "Agenesis of Corpus Callosum",
      "Microphthalmia", "Anophthalmia",
      "Cryptorchidism Congenital", "Hermaphroditism",
      "Diaphragmatic Hernia Congenital",
      "Umbilical Hernia", "Inguinal Hernia",
      "Imperforate Anus", "Rectovaginal Fistula",
      "Renal Agenesis", "Polydactyly",
      "Syndactyly", "Chondrodysplasia",
      "Achondroplasia", "Osteogenesis Imperfecta",
      "Hemimelia", "Phocomelia",
      "Dermoid Cyst", "Branchial Cyst",
      "Thyroglossal Duct Cyst",
      "Collie Eye Anomaly Congenital",
      "Retinal Dysplasia",
      "Congenital Deafness Breed",
      "Congenital Megaesophagus",
      "Congenital Hypothyroidism Breed",
      "Glycogen Storage Disease Congenital",
      "Lysosomal Storage Disease Congenital",
      "Pyruvate Kinase Deficiency",
      "Phosphofructokinase Deficiency",
      "Copper Storage Disease",
      "Von Willebrand Disease Congenital",
      "Factor VII Deficiency Congenital",
      "Cystinuria",
    ],
    // ═══ SURGERY (General / Soft Tissue) ═══
    surgery: [
      "Splenectomy Indications", "Splenic Torsion",
      "Liver Lobectomy", "Cholecystectomy",
      "Gastropexy", "Intestinal Resection Anastomosis",
      "Colectomy", "Subtotal Colectomy",
      "Cystotomy", "Urethrostomy",
      "Perineal Urethrostomy", "Scrotal Urethrostomy",
      "Nephrectomy", "Adrenalectomy",
      "Thyroidectomy", "Parathyroidectomy",
      "Total Ear Canal Ablation Surgery",
      "Lateral Wall Resection",
      "Salivary Gland Excision",
      "Laryngeal Tieback", "Arytenoid Lateralization",
      "Soft Palate Resection", "Nares Widening",
      "Lung Lobectomy", "Thoracotomy",
      "Pericardiectomy", "Patent Ductus Arteriosus Ligation",
      "Diaphragmatic Hernia Repair",
      "Perineal Hernia Repair",
      "Abdominal Wall Hernia Repair",
      "Wound Closure Techniques", "Skin Flap Surgery",
      "Skin Graft", "Negative Pressure Wound Therapy",
      "Limb Amputation", "Tail Amputation",
      "Digit Amputation",
      "Femoral Head Ostectomy", "Triple Pelvic Osteotomy",
      "Tibial Plateau Leveling Osteotomy",
      "Tibial Tuberosity Advancement",
      "Extracapsular Suture Repair",
    ],
    // ═══ PAIN / REHABILITATION ═══
    pain_rehab: [
      "Chronic Pain Syndrome", "Neuropathic Pain",
      "Cancer Pain", "Postoperative Pain Management",
      "Osteoarthritis Pain", "Multimodal Analgesia",
      "Physical Rehabilitation", "Hydrotherapy",
      "Acupuncture in Veterinary Medicine",
      "Laser Therapy", "Therapeutic Ultrasound",
      "Electroacupuncture", "TENS Therapy",
      "Range of Motion Exercises",
      "Weight Management Program",
      "Geriatric Wellness", "Palliative Care",
      "Hospice Care",
    ],
    // ═══ WAVE 2: BREED-SPECIFIC EXPANDED (Dogs) ═══
    breed_specific_dog_w2: [
      // Labrador Retriever
      "Labrador Retriever Elbow Dysplasia", "Labrador Retriever Hip Dysplasia",
      "Labrador Retriever Centronuclear Myopathy", "Labrador Retriever Progressive Retinal Atrophy",
      "Labrador Retriever Tricuspid Valve Dysplasia", "Labrador Retriever Nasal Parakeratosis",
      // Golden Retriever
      "Golden Retriever Ichthyosis", "Golden Retriever Pigmentary Uveitis",
      "Golden Retriever Subvalvular Aortic Stenosis", "Golden Retriever Muscular Dystrophy",
      // German Shepherd
      "German Shepherd Exocrine Pancreatic Insufficiency", "German Shepherd Hemophilia A",
      "German Shepherd Chronic Superficial Keratitis", "German Shepherd Panosteitis",
      "German Shepherd Furunculosis", "German Shepherd Elbow Dysplasia",
      // Bulldog / Brachycephalic
      "English Bulldog Hemivertebra", "English Bulldog Entropion",
      "English Bulldog Cherry Eye", "English Bulldog Hip Dysplasia",
      "English Bulldog Patellar Luxation", "English Bulldog Urethral Prolapse",
      "French Bulldog Brachycephalic Syndrome", "French Bulldog Ear Infections",
      "Pug Encephalitis", "Pug Corneal Ulcer", "Pug Pigmentary Keratopathy",
      "Pug Entropion", "Pug Necrotizing Meningoencephalitis",
      "Boston Terrier Cherry Eye", "Boston Terrier Corneal Dystrophy",
      "Boston Terrier Deafness", "Boston Terrier Mast Cell Tumor",
      // Small Breeds
      "Yorkshire Terrier Hepatic Lipidosis", "Yorkshire Terrier Portosystemic Shunt",
      "Yorkshire Terrier Tracheal Collapse", "Yorkshire Terrier Hypoglycemia",
      "Maltese Shaker Syndrome", "Maltese Portosystemic Shunt",
      "Chihuahua Hydrocephalus", "Chihuahua Patellar Luxation",
      "Chihuahua Tracheal Collapse", "Chihuahua Molera",
      "Pomeranian Alopecia X", "Pomeranian Patellar Luxation",
      "Pomeranian Tracheal Collapse", "Pomeranian Cryptorchidism",
      "Toy Poodle Legg Calve Perthes", "Toy Poodle Patellar Luxation",
      "Miniature Poodle Addisons Disease", "Standard Poodle Sebaceous Adenitis",
      "Dachshund Intervertebral Disc Disease", "Dachshund Acanthosis Nigricans",
      "Dachshund Lafora Disease", "Dachshund Pattern Baldness",
      "Jack Russell Terrier Lens Luxation", "Jack Russell Terrier Ataxia",
      "Jack Russell Terrier Myasthenia Gravis",
      "Shih Tzu Keratoconjunctivitis Sicca", "Shih Tzu Renal Dysplasia",
      "Shih Tzu Urolithiasis", "Cavalier King Charles Spaniel Episodic Falling",
      // Medium Breeds
      "Beagle Epilepsy", "Beagle Factor VII Deficiency",
      "Beagle Cherry Eye", "Beagle Musladin Lueke Syndrome",
      "Border Collie Collie Eye Anomaly", "Border Collie Epilepsy",
      "Border Collie Trapped Neutrophil Syndrome", "Border Collie Neuronal Ceroid Lipofuscinosis",
      "Australian Shepherd MDR1 Sensitivity", "Australian Shepherd Cataracts",
      "Australian Shepherd Epilepsy", "Australian Shepherd Hip Dysplasia",
      "English Springer Spaniel Phosphofructokinase Deficiency",
      "English Springer Spaniel Fucosidosis",
      "Cocker Spaniel Phosphofructokinase Deficiency",
      "Cocker Spaniel Familial Nephropathy",
      "Staffordshire Bull Terrier L2 Hydroxyglutaric Aciduria",
      "Bull Terrier Lethal Acrodermatitis", "Bull Terrier Polycystic Kidney Disease",
      "Bull Terrier Compulsive Tail Chasing",
      "Basenji Fanconi Syndrome", "Basenji Immunoproliferative Enteropathy",
      "Chinese Shar-Pei Entropion", "Shar-Pei Cutaneous Mucinosis",
      "Dalmatian Stone Disease", "Dalmatian Laryngeal Paralysis Polyneuropathy",
      // Large / Giant Breeds
      "Great Dane Dilated Cardiomyopathy", "Great Dane Osteosarcoma",
      "Great Dane Happy Tail Syndrome", "Great Dane Hypertrophic Osteodystrophy",
      "Newfoundland Subvalvular Aortic Stenosis", "Newfoundland Cystinuria",
      "Newfoundland Dilated Cardiomyopathy",
      "Saint Bernard Osteochondritis Dissecans", "Saint Bernard Entropion",
      "Saint Bernard Dilated Cardiomyopathy",
      "Irish Wolfhound Dilated Cardiomyopathy", "Irish Wolfhound Osteosarcoma",
      "Irish Wolfhound Pneumonia", "Irish Wolfhound Portosystemic Shunt",
      "Bernese Mountain Dog Meningitis", "Bernese Mountain Dog Glomerulonephritis",
      "Weimaraner Hypertrophic Osteodystrophy", "Weimaraner Spinal Dysraphism",
      "Weimaraner Immunodeficiency",
      "Rottweiler Parvoviral Enteritis Susceptibility",
      "Rottweiler Cranial Cruciate Ligament Disease",
      "Doberman Von Willebrand Disease", "Doberman Cervical Spondylomyelopathy",
      "Doberman Hypothyroidism", "Doberman Hepatitis",
      // Terrier breeds
      "West Highland White Terrier Craniomandibular Osteopathy",
      "West Highland White Terrier Legg Calve Perthes",
      "Cairn Terrier Craniomandibular Osteopathy",
      "Scottish Terrier Scottie Cramp", "Scottish Terrier Bladder Cancer",
      "Airedale Terrier Cerebellar Hypoplasia",
      "Kerry Blue Terrier Cerebellar Abiotrophy",
      // Sighthound breeds
      "Greyhound Osteosarcoma", "Greyhound Pannus",
      "Greyhound Corns on Footpads", "Greyhound Neuropathy",
      "Whippet Bully Whippet Syndrome", "Whippet Pattern Baldness",
      // Working / Herding
      "Siberian Husky Uveodermatologic Syndrome", "Siberian Husky Zinc Responsive Dermatosis",
      "Siberian Husky Corneal Dystrophy", "Siberian Husky Juvenile Cataracts",
      "Akita Autoimmune Diseases", "Akita Sebaceous Adenitis",
      "Akita Uveodermatologic Syndrome",
      "Collie Dermatomyositis", "Collie Cyclic Neutropenia",
      "Collie Ivermectin Sensitivity", "Shetland Sheepdog Dermatomyositis",
      "Belgian Malinois Epilepsy", "Belgian Tervuren Epilepsy",
    ],
    // ═══ WAVE 2: BREED-SPECIFIC EXPANDED (Cats) ═══
    breed_specific_cat_w2: [
      "Persian Cat Polycystic Kidney Disease Detail",
      "Persian Cat Dermatophytosis Predisposition",
      "Persian Cat Corneal Sequestrum", "Persian Cat Entropion",
      "Persian Cat Idiopathic Facial Dermatitis",
      "Siamese Cat Bronchial Asthma", "Siamese Cat Cutaneous Asthenia",
      "Siamese Cat Convergent Strabismus", "Siamese Cat Nystagmus",
      "Siamese Cat Intestinal Adenocarcinoma",
      "Maine Coon Hip Dysplasia", "Maine Coon Spinal Muscular Atrophy",
      "Maine Coon Polydactyly",
      "Ragdoll Feline Hyperesthesia", "Ragdoll Bladder Stones",
      "Bengal Cat Flat Chested Kitten Syndrome", "Bengal Cat Distal Neuropathy",
      "Bengal Cat Patellar Luxation",
      "Abyssinian Cat Retinal Degeneration", "Abyssinian Cat Pyruvate Kinase Deficiency",
      "Abyssinian Cat Gingivitis",
      "Burmese Cat Feline Orofacial Pain Syndrome",
      "Burmese Cat Congenital Keratoconjunctivitis Sicca",
      "Scottish Fold Osteochondrodysplasia Detail",
      "Scottish Fold Polycystic Kidney Disease",
      "Sphynx Cat Hypertrophic Cardiomyopathy", "Sphynx Cat Urticaria Pigmentosa",
      "Sphynx Cat Hereditary Myopathy",
      "Devon Rex Hereditary Myopathy", "Devon Rex Malassezia Dermatitis",
      "Cornish Rex Hypotrichosis", "Cornish Rex Vitamin K Dependent Coagulopathy",
      "Norwegian Forest Cat Glycogen Storage Disease",
      "Norwegian Forest Cat Pyruvate Kinase Deficiency",
      "British Shorthair Hemophilia B", "British Shorthair Hypertrophic Cardiomyopathy",
      "British Shorthair Polycystic Kidney Disease",
      "Birman Cat Corneal Dermoid", "Birman Cat Neutrophil Granulation Anomaly",
      "Manx Cat Spina Bifida", "Manx Cat Megacolon",
      "Manx Cat Sacrocaudal Dysgenesis",
      "Somali Cat Pyruvate Kinase Deficiency", "Somali Cat Retinal Degeneration",
      "Oriental Shorthair Amyloidosis", "Oriental Shorthair Dilated Cardiomyopathy",
    ],
    // ═══ WAVE 2: CARDIAC EXPANDED ═══
    cardiac_w2: [
      "Right Sided Heart Failure", "Left Sided Heart Failure",
      "Biventricular Heart Failure", "High Output Heart Failure",
      "Tricuspid Regurgitation", "Mitral Regurgitation",
      "Aortic Regurgitation", "Pulmonic Regurgitation",
      "Cardiac Syncope", "Vasovagal Syncope",
      "Premature Ventricular Complexes", "Premature Atrial Complexes",
      "Sinus Bradycardia", "Sinus Tachycardia",
      "Junctional Rhythm", "Idioventricular Rhythm",
      "Atrial Flutter", "Atrial Standstill",
      "Ventricular Fibrillation", "Asystole",
      "Pericardial Constriction", "Cardiac Rhabdomyoma",
      "Endocardiosis", "Valvular Endocarditis",
      "Myocardial Infarction", "Myocardial Contusion",
      "Cardiac Troponin Elevation", "Cardiac Neoplasia Overview",
      "Heart Base Tumor", "Ectopic Atrial Tachycardia",
      "Patent Foramen Ovale", "Ebstein Anomaly",
    ],
    // ═══ WAVE 2: RESPIRATORY EXPANDED ═══
    respiratory_w2: [
      "Parenchymal Lung Disease", "Interstitial Lung Disease",
      "Pulmonary Hemorrhage", "Pulmonary Parasitic Disease",
      "Aelurostrongylus Abstrusus", "Oslerus Osleri",
      "Paragonimus Kellicotti", "Crenosoma Vulpis",
      "Laryngeal Collapse", "Laryngeal Neoplasia",
      "Laryngospasm", "Epiglottitis",
      "Tracheal Stent Complications", "Tracheitis",
      "Lower Airway Disease", "Feline Bronchial Disease",
      "Pulmonary Alveolar Proteinosis", "Pulmonary Lymphomatoid Granulomatosis",
      "Stertor and Stridor", "Reverse Sneezing",
      "Nasal Discharge Differential", "Epistaxis",
      "Rhinitis Chronic Feline", "Rhinitis Allergic",
      "Nasal Lymphoma", "Nasal Adenocarcinoma",
      "Nasopharyngeal Mass", "Maxillary Sinus Disease",
      "Bronchopneumonia Neonatal", "Bordetella Bronchiseptica Infection",
    ],
    // ═══ WAVE 2: GASTROINTESTINAL EXPANDED ═══
    gastrointestinal_w2: [
      "Esophageal Diverticulum", "Esophageal Neoplasia",
      "Esophageal Perforation", "Cricopharyngeal Dysphagia",
      "Gastric Motility Disorder", "Gastric Polyp",
      "Gastric Outflow Obstruction", "Chronic Hypertrophic Pyloric Gastropathy",
      "Duodenal Ulcer", "Jejunal Hemorrhage",
      "Intestinal Mast Cell Tumor", "Intestinal Carcinoid",
      "Intestinal Pythiosis", "Intestinal Histoplasmosis",
      "Cecal Inversion", "Typhlitis",
      "Colorectal Polyp", "Colorectal Carcinoma",
      "Rectoanal Disease", "Perineal Fistula Detail",
      "Proctitis", "Anorectal Stricture",
      "Fecal Incontinence", "Chronic Diarrhea Diagnostic Approach",
      "Chronic Vomiting Diagnostic Approach",
      "Malabsorption Syndrome", "Maldigestion Syndrome",
      "Ascites Differential Diagnosis",
      "Mesenteric Lymphadenopathy", "Mesenteric Root Tumor",
      "Retroperitoneal Mass", "Intra-abdominal Adhesions",
      "Gastric Erosion", "Gastrointestinal Perforation",
    ],
    // ═══ WAVE 2: HEPATIC EXPANDED ═══
    hepatic_w2: [
      "Hepatic Abscess Feline", "Hepatic Mass Differential",
      "Hepatic Nodular Regeneration", "Hepatic Hemangioma",
      "Hepatic Hemangiosarcoma", "Hepatic Carcinoid",
      "Hepatic Myelolipoma", "Gallbladder Carcinoma",
      "Gallbladder Rupture", "Bile Duct Obstruction",
      "Bile Duct Carcinoma Detail", "Common Bile Duct Obstruction",
      "Extrahepatic Biliary Disease", "Intrahepatic Biliary Disease",
      "Hepatitis Chronic Canine", "Hepatitis Chronic Feline",
      "Drug Induced Liver Injury", "Aflatoxin Hepatopathy",
      "Xylitol Hepatotoxicity", "Phenobarbital Hepatotoxicity",
      "NSAID Hepatotoxicity", "Azole Hepatotoxicity",
      "Hepatoportal Microvascular Dysplasia",
      "Hepatic Glycogen Storage",
      "Feline Triaditis Detail",
      "Suppurative Cholangitis Neutrophilic",
      "Lymphocytic Cholangitis",
      "Liver Fluke Infection",
      "Hepatic Cyst", "Hepatic Leiomyosarcoma",
    ],
    // ═══ WAVE 2: RENAL / URINARY EXPANDED ═══
    renal_w2: [
      "Chronic Kidney Disease Stage 1", "Chronic Kidney Disease Stage 2",
      "Chronic Kidney Disease Stage 3", "Chronic Kidney Disease Stage 4",
      "Acute on Chronic Kidney Disease", "Renal Secondary Hyperparathyroidism",
      "Uremic Gastritis", "Uremic Stomatitis",
      "Uremic Pericarditis",
      "Renal Infarction", "Renal Abscess",
      "Perinephric Pseudocyst", "Renal Hematoma",
      "Ethylene Glycol Nephrotoxicity", "Aminoglycoside Nephrotoxicity",
      "NSAID Nephrotoxicity", "Lily Nephrotoxicity",
      "Grape Raisin Nephrotoxicity",
      "Glomerulonephritis Membranous", "Glomerulonephritis Membranoproliferative",
      "Minimal Change Disease", "Focal Segmental Glomerulosclerosis",
      "IgA Nephropathy",
      "Tubulointerstitial Nephritis", "Renal Tubular Necrosis",
      "Obstructive Uropathy", "Ureteral Obstruction",
      "Ureteral Calculus", "Subcutaneous Ureteral Bypass",
      "Ureteral Stent Complications", "Ureteral Stricture",
      "Bladder Rupture", "Bladder Diverticulum",
      "Urethral Rupture", "Urethral Neoplasia",
      "Patent Urachus", "Vesicoureteral Reflux",
      "Urinary Catheter Complications",
      "Peritoneal Dialysis", "Hemodialysis in Veterinary Medicine",
    ],
    // ═══ WAVE 2: ENDOCRINE EXPANDED ═══
    endocrine_w2: [
      "Diabetes Mellitus Type 1", "Diabetes Mellitus Type 2",
      "Transient Diabetes Mellitus Feline",
      "Insulin Resistance", "Diabetic Cataract",
      "Diabetic Hyperosmolar Syndrome", "Euglycemic Diabetic Ketoacidosis",
      "Hyperadrenocorticism Differential Diagnosis",
      "Trilostane Therapy", "Mitotane Therapy",
      "Adrenal Crisis", "Adrenal Incidentaloma",
      "Bilateral Adrenalectomy",
      "Thyroid Storm", "Thyroiditis Autoimmune",
      "Euthyroid Sick Syndrome", "Thyroid Nodule",
      "Radioiodine Therapy Feline",
      "Hypoparathyroidism Postoperative", "Hypocalcemic Crisis",
      "Multiple Endocrine Neoplasia Detail",
      "Ectopic ACTH Syndrome", "Growth Hormone Deficiency",
      "Alopecia Endocrine Pattern",
      "Adrenal Hemorrhage", "Adrenal Pheochromocytoma Detail",
      "Paraganglioma", "Glucagonoma",
      "Gastrinoma", "Somatostatinoma",
    ],
    // ═══ WAVE 2: NEUROLOGY EXPANDED ═══
    neurology_w2: [
      "Cervical Disc Disease Detail", "Thoracolumbar Disc Disease Detail",
      "Type I Disc Extrusion", "Type II Disc Protrusion",
      "Type III Disc Extrusion", "Acute Non-Compressive Nucleus Pulposus Extrusion",
      "Chronic Disc Disease", "Disc Associated Wobbler Syndrome",
      "Osseous Associated Wobbler Syndrome",
      "Spinal Cord Compression", "Spinal Cord Infarction",
      "Spinal Cord Edema", "Spinal Subarachnoid Cyst",
      "Spinal Empyema", "Vertebral Osteomyelitis",
      "Discospondylitis", "Vertebral Fracture Luxation",
      "Peripheral Nerve Tumor", "Nerve Root Tumor",
      "Trigeminal Nerve Tumor", "Optic Nerve Tumor",
      "Peripheral Neuropathy", "Distal Polyneuropathy",
      "Laryngeal Paralysis Polyneuropathy Complex",
      "Chronic Inflammatory Demyelinating Polyneuropathy",
      "Acute Idiopathic Polyradiculoneuritis Detail",
      "Degenerative Lumbosacral Stenosis",
      "Pilonidal Sinus", "Dermoid Sinus Rhodesian Ridgeback",
      "Intracranial Hypertension", "Brain Herniation",
      "Cerebral Edema", "Traumatic Brain Injury Detail",
      "Canine Cognitive Dysfunction Detail",
      "Feline Cognitive Dysfunction",
      "Focal Seizure", "Generalized Seizure",
      "Psychomotor Seizure", "Refractory Epilepsy",
      "Anticonvulsant Responsive Tremor",
      "Head Tremor Syndrome", "Intention Tremor",
      "Feline Hyperesthesia Syndrome Neurologic",
      "Central Nervous System Vasculitis",
      "Ischemic Encephalopathy Feline",
      "Hepatic Encephalopathy Detail",
      "Thiamine Deficiency Encephalopathy",
      "Lead Encephalopathy",
    ],
    // ═══ WAVE 2: OPHTHALMOLOGY EXPANDED ═══
    ophthalmology_w2: [
      "Descemetocele", "Corneal Laceration",
      "Corneal Foreign Body", "Corneal Endothelial Dystrophy",
      "Bullous Keratopathy", "Band Keratopathy",
      "Crystalline Keratopathy", "Pigmentary Keratitis",
      "Eosinophilic Keratoconjunctivitis", "Herpes Viral Keratitis Feline",
      "Dendritic Ulcer", "Deep Corneal Ulcer",
      "Corneal Perforation", "Corneal Transplant Complications",
      "Anterior Chamber Paracentesis",
      "Pupillary Block Glaucoma", "Open Angle Glaucoma",
      "Closed Angle Glaucoma", "Glaucoma Emergency Management",
      "Phthisis Bulbi", "Enucleation Indications",
      "Exenteration Indications",
      "Vitreous Degeneration", "Vitreal Hemorrhage",
      "Hyaloid Artery Remnant", "Asteroid Hyalosis",
      "Chorioretinitis", "Retinitis",
      "Hypertensive Retinopathy", "Diabetic Retinopathy",
      "Retinal Dysplasia Detail", "Retinal Hemorrhage Detail",
      "Optic Nerve Hypoplasia", "Papilledema",
      "Eyelid Mass", "Eyelid Laceration",
      "Meibomian Gland Tumor", "Eyelid Agenesis",
      "Third Eyelid Protrusion", "Third Eyelid Tumor",
      "Plasmoma Third Eyelid", "Scrolled Third Eyelid",
      "Prolapsed Gland Third Eyelid",
      "Orbital Abscess", "Orbital Cellulitis",
      "Orbital Tumor", "Zygomatic Mucocele",
      "Dacryocystitis", "Nasolacrimal Duct Atresia",
    ],
    // ═══ WAVE 2: ORTHOPEDIC EXPANDED ═══
    orthopedic_w2: [
      "TPLO Complications", "TTA Complications",
      "Extracapsular Repair Complications", "Meniscal Tear",
      "Cranial Drawer Sign", "Tibial Thrust",
      "Collateral Ligament Injury", "Shoulder Instability",
      "Medial Shoulder Instability", "Shoulder Osteochondritis Dissecans",
      "Elbow Incongruity", "Elbow Luxation",
      "Carpal Fracture", "Metacarpal Fracture",
      "Metatarsal Fracture", "Scapular Fracture",
      "Ilial Fracture", "Sacroiliac Luxation",
      "Acetabular Fracture", "Physeal Fracture Salter Harris",
      "Stress Fracture", "Nonunion Fracture",
      "Delayed Union", "Malunion",
      "Osteomyelitis Chronic", "Sequestrum Bone",
      "Bone Graft Complications", "External Fixator Complications",
      "Intramedullary Pin Migration",
      "Total Hip Replacement Complications",
      "Femoral Head Ostectomy Detail",
      "Juvenile Pubic Symphysiodesis",
      "Patellar Tendon Rupture", "Quadriceps Contracture",
      "Iliopsoas Strain", "Sesamoid Disease",
      "Accessory Carpal Bone Fracture",
      "Calcaneal Fracture", "Talar Fracture",
      "Congenital Elbow Luxation", "Congenital Shoulder Luxation",
      "Eosinophilic Panosteitis", "Craniomandibular Osteopathy",
      "Multiple Cartilaginous Exostoses",
    ],
    // ═══ WAVE 2: DERMATOLOGY EXPANDED ═══
    dermatology_w2: [
      "Bacterial Pododermatitis", "Interdigital Furunculosis",
      "Interdigital Cyst", "Folliculitis Bacterial",
      "Folliculitis Fungal", "Folliculitis Parasitic",
      "Demodicosis Feline", "Demodex Injai",
      "Demodex Gatoi", "Notoedres Cati",
      "Cheyletiella Dermatitis", "Otodectes Cynotis",
      "Harvest Mite Infestation", "Flea Infestation Control",
      "Tick Bite Reaction", "Lice Infestation Canine",
      "Cuterebra Larva Migration", "Myiasis Detail",
      "Dermatophyte Culture Interpretation",
      "Malassezia Otitis", "Malassezia Pododermatitis",
      "Candidiasis Cutaneous", "Subcutaneous Mycosis",
      "Phaeohyphomycosis", "Cutaneous Pythiosis",
      "Idiopathic Sterile Granuloma", "Cutaneous Histiocytosis",
      "Langerhans Cell Histiocytosis", "Reactive Histiocytosis",
      "Cutaneous Epitheliotropic Lymphoma", "Non-Epitheliotropic Cutaneous Lymphoma",
      "Vaccine Site Reaction", "Injection Site Alopecia",
      "Alopecia Areata", "Traction Alopecia",
      "Telogen Effluvium", "Anagen Defluxion",
      "Post Clipping Alopecia", "Cyclic Flank Alopecia Detail",
      "Vitiligo", "Lentigo Simplex Feline",
      "Nasal Depigmentation", "Mucocutaneous Pyoderma",
      "Chin Acne Feline", "Feline Eosinophilic Granuloma Complex",
      "Eosinophilic Plaque Feline", "Indolent Ulcer Lip Feline",
      "Linear Granuloma Feline", "Mosquito Bite Hypersensitivity",
      "Solar Dermatitis", "Actinic Keratosis",
      "Squamous Cell Carcinoma Solar", "Skin Tag",
      "Epidermal Inclusion Cyst", "Follicular Cyst",
      "Apocrine Cyst", "Calcinosis Circumscripta",
    ],
    // ═══ WAVE 2: ONCOLOGY EXPANDED ═══
    oncology_w2: [
      "Lymphoma B Cell", "Lymphoma T Cell",
      "Lymphoma High Grade", "Lymphoma Low Grade",
      "Lymphoma Indolent", "Lymphoma Stage I to V",
      "Splenic Hemangiosarcoma Detail", "Dermal Hemangiosarcoma",
      "Visceral Hemangiosarcoma", "Right Atrial Hemangiosarcoma",
      "Appendicular Osteosarcoma", "Axial Osteosarcoma",
      "Extraskeletal Osteosarcoma", "Osteosarcoma Limb Sparing",
      "Mast Cell Tumor Grade I", "Mast Cell Tumor Grade II",
      "Mast Cell Tumor Grade III", "Mast Cell Tumor Visceral",
      "Feline Mast Cell Tumor Cutaneous", "Feline Mast Cell Tumor Splenic",
      "Feline Mast Cell Tumor Intestinal",
      "Injection Site Sarcoma Detail", "Vaccine Associated Sarcoma Detail",
      "Fibrosarcoma Oral", "Fibrosarcoma Appendicular",
      "Neurofibrosarcoma", "Malignant Peripheral Nerve Sheath Tumor",
      "Melanoma Digital", "Melanoma Mucocutaneous",
      "Melanoma Vaccine", "Amelanotic Melanoma",
      "Squamous Cell Carcinoma Tonsillar", "Squamous Cell Carcinoma Digital",
      "Squamous Cell Carcinoma Nasal Planum", "Squamous Cell Carcinoma Feline Oral",
      "Mammary Carcinoma Complex Type", "Mammary Carcinoma Simple Type",
      "Mammary Inflammatory Carcinoma", "Mammary Mixed Tumor",
      "Canine Mammary Tumor Staging",
      "Prostatic Adenocarcinoma Detail", "Bladder Transitional Cell Carcinoma Detail",
      "Urethral Carcinoma",
      "Nasal Adenocarcinoma Detail", "Nasal Chondrosarcoma",
      "Thymoma Detail", "Thymic Lymphoma",
      "Insulinoma Detail", "Glucagonoma Syndrome",
      "Adrenal Cortical Tumor", "Adrenal Medullary Tumor",
      "Parathyroid Tumor", "Thyroid Adenoma",
      "Ectopic Thyroid Tumor",
      "Cholangiocellular Carcinoma", "Hepatoid Gland Tumor",
      "Ceruminous Gland Carcinoma",
      "Chemotherapy Protocols Canine", "Chemotherapy Protocols Feline",
      "Radiation Therapy Veterinary", "Immunotherapy Veterinary",
      "Paraneoplastic Hypercalcemia", "Paraneoplastic Hypoglycemia",
      "Paraneoplastic Neuropathy", "Cancer Staging Systems",
    ],
    // ═══ WAVE 2: INFECTIOUS EXPANDED ═══
    infectious_w2: [
      "Canine Respiratory Coronavirus", "Canine Pneumovirus",
      "Canine Enteric Coronavirus Detail",
      "Canine Adenovirus Type 1", "Canine Adenovirus Type 2",
      "Canine Parainfluenza Virus", "Canine Minute Virus",
      "Feline Morbillivirus", "Feline Foamy Virus",
      "Feline Parvovirus Detail",
      "Borrelia Burgdorferi Detail", "Lyme Nephritis",
      "Ehrlichia Canis", "Ehrlichia Ewingii",
      "Anaplasma Phagocytophilum", "Anaplasma Platys",
      "Neorickettsia Helminthoeca", "Salmon Poisoning Disease",
      "Q Fever Coxiella Burnetii",
      "Yersinia Pestis Veterinary", "Francisella Tularensis Detail",
      "Mycobacterium Avium Complex", "Mycobacterium Leprae Feline",
      "Feline Leprosy Syndrome",
      "L-form Bacterial Infection",
      "Methicillin Resistant Staphylococcus Pseudintermedius",
      "Extended Spectrum Beta-Lactamase Infection",
      "Multidrug Resistant Infection",
      "Blastomycosis Detail", "Histoplasmosis Detail",
      "Coccidioidomycosis Detail", "Cryptococcosis Detail",
      "Aspergillosis Sinonasal", "Aspergillosis Disseminated",
      "Sporotrichosis Detail", "Dermatophyte Pseudomycetoma",
      "Phaeohyphomycosis Systemic", "Hyalohyphomycosis",
      "Pneumocystosis",
      "Babesia Canis", "Babesia Gibsoni",
      "Cytauxzoon Felis Detail",
      "Hepatozoon Canis", "Hepatozoon Americanum",
      "Leishmania Infantum Detail",
      "Sarcocystosis", "Hammondia Infection",
      "Encephalitozoon Cuniculi",
      "Dirofilaria Immitis Detail", "Dirofilaria Repens",
      "Angiostrongylus Vasorum Detail",
      "Spirocerca Lupi", "Ollulanus Tricuspis",
      "Physaloptera Infection", "Baylisascaris Procyonis",
    ],
    // ═══ WAVE 2: TOXICOLOGY EXPANDED ═══
    toxicology_w2: [
      "Corn Lily Toxicosis", "Yew Toxicosis",
      "Foxglove Toxicosis", "Azalea Rhododendron Toxicosis",
      "Dieffenbachia Toxicosis", "Philodendron Toxicosis",
      "Poinsettia Toxicosis", "Tulip Daffodil Toxicosis",
      "Brunfelsia Toxicosis", "Kalanchoe Toxicosis",
      "Compost Toxicosis", "Fertilizer Toxicosis",
      "Herbicide Toxicosis", "Glyphosate Toxicosis",
      "Paraquat Toxicosis", "Insecticide Toxicosis General",
      "Carbamate Toxicosis", "Amitraz Toxicosis",
      "Fipronil Toxicosis", "Neonicotinoid Toxicosis",
      "Afoxolaner Isoxazoline Toxicosis",
      "Ketoconazole Toxicosis", "Methotrexate Toxicosis",
      "Cyclosporine Toxicosis", "Vincristine Extravasation",
      "Doxorubicin Cardiotoxicity", "Cisplatin Nephrotoxicity",
      "Vitamin D Rodenticide Detail", "Second Generation Anticoagulant Rodenticide",
      "First Generation Anticoagulant Rodenticide",
      "Methomyl Toxicosis", "Aldicarb Toxicosis",
      "Carbon Monoxide Poisoning", "Cyanide Toxicosis",
      "Hydrogen Sulfide Toxicosis",
      "Essential Oil Toxicosis", "Tea Tree Oil Toxicosis",
      "Pennyroyal Toxicosis", "Eucalyptus Oil Toxicosis",
      "Nicotine Toxicosis", "Illicit Drug Exposure",
      "Methamphetamine Toxicosis", "Opioid Toxicosis",
      "Gabapentin Toxicosis", "Baclofen Toxicosis",
      "Decongestant Toxicosis Pseudoephedrine",
      "Antihistamine Toxicosis", "Diphenhydramine Toxicosis",
      "Iron Supplement Toxicosis", "Vitamin A Hypervitaminosis",
      "Bread Dough Toxicosis", "Hops Toxicosis",
      "Macadamia Nut Detail", "Dark Chocolate Toxicity Detail",
    ],
    // ═══ WAVE 2: EMERGENCY / CRITICAL CARE EXPANDED ═══
    emergency_w2: [
      "Polytrauma Management", "Trauma Triage Protocol",
      "Hemorrhage Control", "Tourniquet Application",
      "Tracheostomy Emergency", "Chest Tube Placement",
      "Pericardiocentesis", "Abdominocentesis",
      "Thoracocentesis", "Diagnostic Peritoneal Lavage",
      "Central Venous Catheter Placement", "Intraosseous Catheter",
      "Blood Gas Interpretation", "Lactate Monitoring",
      "Fluid Resuscitation Protocol", "Colloid vs Crystalloid",
      "Vasopressor Therapy", "Inotrope Therapy",
      "Mechanical Ventilation Detail", "Non-Invasive Ventilation",
      "High Flow Nasal Oxygen", "Oxygen Cage Therapy",
      "Continuous Rate Infusion Protocols",
      "Acute Anaphylaxis Management", "Epinephrine Administration",
      "Status Epilepticus Emergency Protocol",
      "Diabetic Emergency Management",
      "Hypoglycemia Emergency", "Hyperglycemic Crisis",
      "Addisonian Crisis", "Thyroid Storm Emergency",
      "Acute Tumor Lysis Syndrome", "Malignant Hyperthermia",
      "Fat Embolism Syndrome",
      "Near Drowning Freshwater", "Near Drowning Saltwater",
      "Hanging Strangulation Injury",
      "Blast Injury", "Crush Injury",
      "Compartment Syndrome",
      "Post Cardiac Arrest Care", "Return of Spontaneous Circulation",
      "Targeted Temperature Management",
    ],
    // ═══ WAVE 2: IMMUNOLOGY EXPANDED ═══
    immunology_w2: [
      "Autoimmune Skin Disease Overview", "Autoimmune Hemolytic Anemia Detail",
      "Cold Agglutinin Disease", "Warm Autoimmune Hemolytic Anemia",
      "Secondary Immune Mediated Hemolytic Anemia",
      "Neonatal Isoerythrolysis Detail",
      "Immune Mediated Neutropenia", "Immune Mediated Meningitis",
      "Steroid Responsive Meningitis Arteritis Detail",
      "Immune Mediated Retinitis",
      "Uveodermatologic Syndrome Detail",
      "Dermatomyositis Detail",
      "Masticatory Muscle Myositis Detail",
      "Extraocular Myositis Detail",
      "Immune Complex Disease", "Type III Hypersensitivity Detail",
      "Delayed Type Hypersensitivity", "Contact Hypersensitivity",
      "Drug Induced Immune Mediated Hemolytic Anemia",
      "Drug Induced Thrombocytopenia",
      "Post Vaccinal Immune Mediated Disease",
      "Graft Versus Host Disease",
      "Transplant Rejection",
      "Feline Plasma Cell Pododermatitis",
      "Idiopathic Immune Mediated Polyarthritis",
      "Erosive Polyarthritis",
      "Primary Immunodeficiency", "Secondary Immunodeficiency",
      "Wiskott Aldrich Like Syndrome",
      "Severe Combined Immunodeficiency",
      "Selective Immunoglobulin Deficiency",
      "Complement System Disorders",
    ],
    // ═══ WAVE 2: REPRODUCTIVE EXPANDED ═══
    reproductive_w2: [
      "Ovarian Cyst Detail", "Ovarian Neoplasia Detail",
      "Granulosa Cell Tumor", "Ovarian Teratoma",
      "Uterine Torsion", "Uterine Rupture",
      "Stump Pyometra", "Mucometra",
      "Hydrometra", "Endometritis",
      "Retained Placenta", "Postpartum Hemorrhage",
      "Puerperal Tetany", "Postpartum Metritis",
      "Prolapsed Uterus Detail", "Cervical Dystocia",
      "Fetal Malposition", "Fetal Macrosomia",
      "Singleton Pregnancy", "Superfetation",
      "Canine Brucellosis Reproductive",
      "Reproductive Ultrasonography",
      "Progesterone Monitoring", "Vaginal Cytology",
      "Artificial Insemination Canine", "Semen Evaluation",
      "Azoospermia", "Oligospermia",
      "Testicular Neoplasia Detail", "Sertoli Cell Tumor Detail",
      "Testicular Torsion", "Epididymitis",
      "Transmissible Venereal Tumor Detail",
      "Penile Neoplasia", "Preputial Neoplasia",
      "Balanoposthitis", "Os Penis Fracture",
      "Mammary Gland Hyperplasia Feline",
      "Mammary Fibroadenomatous Change",
      "Galactostasis", "Mastitis Detail",
    ],
    // ═══ WAVE 2: BEHAVIORAL EXPANDED ═══
    behavioral_w2: [
      "Thunderstorm Phobia Detail", "Firework Phobia",
      "Veterinary Visit Anxiety", "Travel Anxiety",
      "Confinement Anxiety", "Barrier Frustration",
      "Leash Reactivity", "Dog Dog Aggression",
      "Owner Directed Aggression", "Stranger Directed Aggression",
      "Pain Induced Aggression", "Idiopathic Aggression",
      "Play Aggression Kitten", "Status Related Aggression",
      "Maternal Aggression", "Food Aggression Detail",
      "Repetitive Motor Behavior", "Shadow Chasing",
      "Light Chasing", "Blanket Sucking",
      "Wool Sucking Feline", "Pica Feline",
      "Overgrooming Feline", "Barbering Behavior",
      "Spraying Behavior Feline", "Middening Feline",
      "Attention Seeking Behavior", "Demand Barking",
      "Night Waking", "Sundowner Syndrome",
      "Canine Senile Dementia", "Nighttime Restlessness",
      "Hyperactivity Canine", "Impulse Control Disorder",
      "Fear Period Puppy", "Socialization Deficit",
      "Environmental Enrichment", "Behavior Modification Protocols",
    ],
    // ═══ WAVE 2: EAR EXPANDED ═══
    ear_w2: [
      "Otitis Externa Chronic", "Otitis Externa Allergic",
      "Otitis Externa Parasitic", "Otitis Externa Ceruminous",
      "Otitis Media Detail", "Otitis Interna Detail",
      "Middle Ear Effusion", "Middle Ear Cholesteatoma",
      "Tympanic Membrane Rupture", "Tympanic Bulla Osteotomy",
      "Bulla Osteotomy Ventral", "Bulla Osteotomy Lateral",
      "Ear Canal Stenosis", "Ear Canal Calcification",
      "Proliferative Otitis External",
      "Aural Hematoma Detail", "Aural Hematoma Surgical Repair",
      "Inflammatory Polyp Middle Ear",
      "Ear Mite Otodectes Detail",
      "Congenital Deafness Breed Predisposition",
      "Acquired Deafness", "Ototoxicity",
      "Vestibular Disease Otogenic",
      "Facial Nerve Damage Otitis",
      "Ear Margin Vasculitis Detail",
      "Ceruminous Gland Hyperplasia",
    ],
    // ═══ WAVE 2: VASCULAR EXPANDED ═══
    vascular_w2: [
      "Aortic Thromboembolism Detail", "Iliac Thrombosis",
      "Portal Vein Thrombosis", "Splenic Vein Thrombosis",
      "Cranial Vena Cava Syndrome", "Caudal Vena Cava Thrombosis",
      "Jugular Vein Thrombosis", "Catheter Associated Thrombosis",
      "Budd Chiari Syndrome", "Portal Hypertension",
      "Arteriovenous Fistula", "Arteriovenous Malformation",
      "Vasculitis Systemic", "Polyarteritis Nodosa Detail",
      "Cutaneous Vasculitis Detail", "Immune Complex Vasculitis",
      "Lymphangitis", "Lymphedema",
      "Chylothorax Vascular", "Chylous Ascites",
      "Lymphatic Malformation",
      "Mesenteric Vascular Disease",
      "Renal Vascular Disease", "Renovascular Hypertension",
      "Peripheral Arterial Disease",
      "Aneurysm", "Aortic Aneurysm",
      "Splenic Artery Aneurysm",
      "Vascular Ring Anomaly Detail",
      "Persistent Left Cranial Vena Cava",
    ],
    // ═══ WAVE 2: ELECTROLYTE EXPANDED ═══
    electrolyte_w2: [
      "Hypokalemia Detail", "Hyperkalemia Detail",
      "Hyponatremia Detail", "Hypernatremia Detail",
      "Hypocalcemia Detail", "Hypercalcemia Detail",
      "Hypochloremia", "Hyperchloremia",
      "Hypomagnesemia Detail", "Hypermagnesemia Detail",
      "Hypophosphatemia Detail", "Hyperphosphatemia Detail",
      "Mixed Acid Base Disorder", "Anion Gap Acidosis",
      "Non Anion Gap Acidosis", "Respiratory Alkalosis Detail",
      "Respiratory Acidosis Detail", "Metabolic Alkalosis Detail",
      "Metabolic Acidosis Detail",
      "Fluid Therapy Maintenance", "Fluid Therapy Replacement",
      "Fluid Therapy Resuscitation",
      "Potassium Supplementation Protocol",
      "Calcium Supplementation Protocol",
      "Refeeding Syndrome", "Tumor Lysis Syndrome Electrolyte",
      "Post Obstructive Diuresis",
      "Diabetic Ketoacidosis Electrolyte Management",
      "Acute Kidney Injury Electrolyte",
      "Chronic Kidney Disease Electrolyte",
    ],
    // ═══ WAVE 2: EXOTIC - RABBIT EXPANDED ═══
    rabbit_w2: [
      "Rabbit Dental Disease Detail", "Rabbit Incisor Malocclusion",
      "Rabbit Molar Elongation", "Rabbit Periapical Abscess",
      "Rabbit Retrobulbar Abscess", "Rabbit Facial Abscess Management",
      "Rabbit GI Stasis Detail", "Rabbit Acute GI Obstruction",
      "Rabbit Cecotrophy Disorder", "Rabbit Hepatic Lipidosis",
      "Rabbit Uterine Adenocarcinoma Detail", "Rabbit Endometrial Hyperplasia",
      "Rabbit Mammary Gland Disease", "Rabbit Testicular Tumor",
      "Rabbit VHD RHDV1", "Rabbit VHD RHDV2",
      "Rabbit Myxomatosis Detail", "Rabbit Myxoma Fibroma",
      "Rabbit Pasteurella Multocida Detail", "Rabbit Pasteurella Upper Respiratory",
      "Rabbit Bordetella Infection", "Rabbit Staphylococcal Infection",
      "Rabbit Encephalitozoon Cuniculi Detail", "Rabbit Head Tilt Differential",
      "Rabbit Spondylosis", "Rabbit Vertebral Fracture Detail",
      "Rabbit Hind Limb Paresis", "Rabbit Spinal Cord Disease",
      "Rabbit Urinary Sludge", "Rabbit Urolithiasis Detail",
      "Rabbit Renal Disease", "Rabbit Obstructive Urolithiasis",
      "Rabbit Pododermatitis Detail", "Rabbit Ulcerative Pododermatitis",
      "Rabbit Ear Canker", "Rabbit Otitis Media Detail",
      "Rabbit Facial Nerve Paralysis",
      "Rabbit Coccidiosis Eimeria", "Rabbit Intestinal Coccidiosis Detail",
      "Rabbit Hepatic Coccidiosis Detail",
      "Rabbit Pinworm Passalurus Ambiguus",
      "Rabbit Cheyletiella Fur Mites",
      "Rabbit Myiasis Fly Strike Detail",
      "Rabbit Dermatophytosis Trichophyton",
      "Rabbit Treponema Cuniculi",
      "Rabbit Anesthesia Complications", "Rabbit Ovariohysterectomy",
      "Rabbit Neutering Technique", "Rabbit Dental Radiography",
      "Rabbit Nutrition Requirements", "Rabbit Diet Related Disease",
    ],
    // ═══ WAVE 2: EXOTIC - GUINEA PIG EXPANDED ═══
    guinea_pig_w2: [
      "Guinea Pig Vitamin C Detailed Deficiency",
      "Guinea Pig Malocclusion Detail", "Guinea Pig Molar Spur",
      "Guinea Pig Incisor Overgrowth", "Guinea Pig Dental Radiography",
      "Guinea Pig Ovarian Cyst Detail", "Guinea Pig Ovarian Neoplasia",
      "Guinea Pig Cystic Endometrial Hyperplasia",
      "Guinea Pig Pneumonia Detail", "Guinea Pig Bordetella Detail",
      "Guinea Pig Streptococcus Pneumoniae",
      "Guinea Pig Chlamydophila Caviae",
      "Guinea Pig Urolithiasis Detail", "Guinea Pig Calcium Metabolism",
      "Guinea Pig Cystitis Detail", "Guinea Pig Urethral Stone",
      "Guinea Pig Pododermatitis Detail", "Guinea Pig Bumblefoot Staging",
      "Guinea Pig Dermatophytosis Trichophyton",
      "Guinea Pig Trixacarus Mange", "Guinea Pig Chirodiscoides Caviae",
      "Guinea Pig Cervical Lymphadenitis Streptobacillus",
      "Guinea Pig GI Stasis Detail", "Guinea Pig Cecal Tympany",
      "Guinea Pig Dystocia Detail", "Guinea Pig Pregnancy Toxemia Detail",
      "Guinea Pig Ketosis",
      "Guinea Pig Diabetes Detail", "Guinea Pig Obesity Detail",
      "Guinea Pig Cardiac Disease", "Guinea Pig Pericardial Effusion",
      "Guinea Pig Lymphoma Detail", "Guinea Pig Leukemia",
      "Guinea Pig Lipoma", "Guinea Pig Trichofolliculoma Detail",
      "Guinea Pig Eye Disease", "Guinea Pig Pea Eye",
      "Guinea Pig Entropion", "Guinea Pig Fatty Eye",
      "Guinea Pig Osteoarthritis", "Guinea Pig Hind Limb Weakness",
    ],
    // ═══ WAVE 2: EXOTIC - HAMSTER EXPANDED ═══
    hamster_w2: [
      "Hamster Wet Tail Detail", "Hamster Proliferative Ileitis",
      "Hamster Lawsonia Intracellularis",
      "Hamster Cheek Pouch Prolapse", "Hamster Cheek Pouch Eversion",
      "Hamster Cheek Pouch Tumor", "Hamster Cheek Pouch Abscess",
      "Hamster Diabetes Detail", "Hamster Diabetes Management",
      "Hamster Dental Overgrowth Detail", "Hamster Dental Abscess",
      "Hamster Lymphoma Detail", "Hamster Cutaneous T-Cell Lymphoma",
      "Hamster Adrenal Tumor Detail", "Hamster Adrenal Cortical Carcinoma",
      "Hamster Thyroid Tumor", "Hamster Uterine Tumor",
      "Hamster Mammary Tumor", "Hamster Melanoma",
      "Hamster Amyloidosis Detail", "Hamster Renal Amyloidosis",
      "Hamster Hepatic Amyloidosis", "Hamster Splenic Amyloidosis",
      "Hamster Congestive Heart Failure Detail", "Hamster Atrial Thrombosis Detail",
      "Hamster Cardiomyopathy", "Hamster Cardiac Calcification",
      "Hamster Polycystic Disease Detail", "Hamster Polycystic Liver",
      "Hamster Demodex Criceti", "Hamster Demodex Aurati",
      "Hamster Skin Abscess", "Hamster Fight Wounds",
      "Hamster Tyzzer Disease Detail", "Hamster Clostridium Piliforme",
      "Hamster Pinworm Syphacia", "Hamster Tapeworm Hymenolepis",
      "Hamster Respiratory Mycoplasmosis",
      "Hamster Sendai Virus",
    ],
    // ═══ WAVE 2: EXOTIC - FERRET EXPANDED ═══
    ferret_w2: [
      "Ferret Adrenal Disease Detail", "Ferret Adrenalectomy",
      "Ferret Adrenal GnRH Agonist Therapy",
      "Ferret Insulinoma Detail", "Ferret Insulinoma Medical Management",
      "Ferret Insulinoma Surgical Management",
      "Ferret Lymphoma Detail", "Ferret Mediastinal Lymphoma",
      "Ferret Cutaneous Lymphoma", "Ferret GI Lymphoma",
      "Ferret Aplastic Anemia Detail", "Ferret Hyperestrogenism Detail",
      "Ferret Distemper Detail", "Ferret Canine Distemper Vaccination",
      "Ferret Influenza Detail", "Ferret Human Influenza",
      "Ferret Coronavirus Detail", "Ferret Systemic Coronavirus Detail",
      "Ferret Epizootic Catarrhal Enteritis Detail",
      "Ferret Helicobacter Mustelae", "Ferret Gastric Ulcer",
      "Ferret GI Foreign Body Detail", "Ferret Trichobezoar",
      "Ferret Cardiomyopathy Detail", "Ferret Dilated Cardiomyopathy",
      "Ferret Hypertrophic Cardiomyopathy",
      "Ferret Heartworm Detail", "Ferret Heartworm Prevention",
      "Ferret Splenomegaly Detail", "Ferret Extramedullary Hematopoiesis",
      "Ferret Dental Disease Detail", "Ferret Dental Calculus",
      "Ferret Skin Tumor Detail", "Ferret Mast Cell Tumor Detail",
      "Ferret Sebaceous Epithelioma", "Ferret Basal Cell Tumor",
      "Ferret Chordoma Detail", "Ferret Tail Tip Chordoma",
      "Ferret Aleutian Disease Detail", "Ferret ADV Testing",
      "Ferret Proliferative Bowel Disease Detail",
      "Ferret Renal Cyst Detail", "Ferret Renal Carcinoma",
      "Ferret Urolithiasis Detail", "Ferret Prostatic Disease",
      "Ferret Ear Mites Detail", "Ferret Sarcoptic Mange",
    ],
    // ═══ WAVE 2: EXOTIC - CHINCHILLA EXPANDED ═══
    chinchilla_w2: [
      "Chinchilla Dental Disease Detail", "Chinchilla Molar Elongation",
      "Chinchilla Incisor Malocclusion", "Chinchilla Dental Root Elongation",
      "Chinchilla Dental Abscess", "Chinchilla Apical Root Abscess",
      "Chinchilla GI Stasis Detail", "Chinchilla Cecal Tympany",
      "Chinchilla Enterotoxemia", "Chinchilla Intussusception",
      "Chinchilla Bloat Detail", "Chinchilla Megacolon",
      "Chinchilla Dermatophytosis Detail", "Chinchilla Trichophyton Mentagrophytes",
      "Chinchilla Fur Chewing", "Chinchilla Cotton Fur",
      "Chinchilla Fur Slip Detail", "Chinchilla Alopecia",
      "Chinchilla Heatstroke Detail", "Chinchilla Thermal Stress",
      "Chinchilla Pneumonia Detail", "Chinchilla Bordetella Infection",
      "Chinchilla Pseudomonas Infection",
      "Chinchilla Otitis Media Detail", "Chinchilla Vestibular Disease",
      "Chinchilla Eye Disease", "Chinchilla Conjunctivitis Detail",
      "Chinchilla Corneal Ulcer", "Chinchilla Cataracts",
      "Chinchilla Diabetes Detail", "Chinchilla Diabetes Management",
      "Chinchilla Cardiomyopathy Detail", "Chinchilla Heart Murmur",
      "Chinchilla Listeriosis Detail", "Chinchilla Yersinia Infection",
      "Chinchilla Giardiasis", "Chinchilla Cryptosporidiosis",
      "Chinchilla Rectal Prolapse Detail", "Chinchilla Penile Hair Ring",
      "Chinchilla Pyometra", "Chinchilla Dystocia",
      "Chinchilla Seizure Detail", "Chinchilla Lead Toxicosis",
      "Chinchilla Calcium Deficiency",
      "Chinchilla Nutrition Requirements", "Chinchilla Hay Impaction",
    ],
    // ═══ WAVE 2: EXOTIC - RAT EXPANDED ═══
    rat_w2: [
      "Rat Mycoplasma Pulmonis Detail", "Rat Chronic Respiratory Disease",
      "Rat Sendai Virus", "Rat Sialodacryoadenitis Virus",
      "Rat Coronavirus", "Rat Parvoviruses",
      "Rat Mammary Fibroadenoma", "Rat Mammary Adenocarcinoma",
      "Rat Mammary Tumor Surgical Removal",
      "Rat Pituitary Adenoma Detail", "Rat Pituitary Tumor Symptoms",
      "Rat Zymbal Gland Tumor Detail", "Rat Keratoacanthoma",
      "Rat Fibrosarcoma Detail", "Rat Histiocytic Sarcoma",
      "Rat Leukemia", "Rat Large Granular Lymphocyte Leukemia",
      "Rat Ulcerative Dermatitis Detail", "Rat Self-Mutilation",
      "Rat Ringtail Detail", "Rat Tail Necrosis",
      "Rat Bumblefoot Detail", "Rat Staphylococcal Pododermatitis",
      "Rat Chromodacryorrhea Detail", "Rat Porphyrin Staining",
      "Rat Renal Disease Detail", "Rat Chronic Progressive Nephropathy",
      "Rat Heart Failure Detail", "Rat Myocardial Degeneration",
      "Rat Malocclusion Detail", "Rat Incisor Overgrowth",
      "Rat Demodex Mites", "Rat Radfordia Mites",
      "Rat Polyoma Virus",
      "Rat Pinworm Syphacia Muris", "Rat Tapeworm Hymenolepis",
      "Rat Barbering Detail", "Rat Dominance Barbering",
      "Rat Hind Limb Degeneration", "Rat Degenerative Myelopathy",
      "Rat Stroke Detail", "Rat Middle Cerebral Artery Occlusion",
      "Rat Abscess", "Rat Preputial Gland Abscess",
      "Rat Obesity", "Rat Diet Related Disease",
    ],
    // ═══ WAVE 2: EXOTIC - AVIAN EXPANDED ═══
    avian_w2: [
      "Avian Psittacosis Detail", "Avian Chlamydia Psittaci",
      "Avian Aspergillosis Detail", "Avian Respiratory Aspergillosis",
      "Avian Air Sac Aspergillosis", "Avian Aspergillus Fumigatus",
      "Avian PDD Detail", "Avian Proventricular Dilatation Disease Diagnosis",
      "Avian Polyomavirus Detail", "Avian Budgerigar Fledgling Disease",
      "Avian Bornavirus Detail", "Avian Ganglioneuritis",
      "PBFD Detail", "PBFD Diagnosis and Treatment",
      "Avian Poxvirus Detail", "Avian Dry Pox", "Avian Wet Pox",
      "Avian Candidiasis Detail", "Avian Crop Candidiasis",
      "Avian Megabacteriosis Detail", "Avian Macrorhabdus Ornithogaster",
      "Avian Gout Articular", "Avian Gout Visceral",
      "Avian Egg Binding Detail", "Avian Egg Yolk Peritonitis",
      "Avian Chronic Egg Laying", "Avian Reproductive Disease",
      "Avian Cloacal Papilloma", "Avian Cloacal Prolapse Detail",
      "Avian Feather Picking Detail", "Avian Feather Destructive Behavior",
      "Avian Self Mutilation Detail", "Avian Behavioral Screaming",
      "Avian Heavy Metal Toxicosis Detail", "Avian Lead Poisoning",
      "Avian Zinc Poisoning", "Avian Copper Toxicosis",
      "Avian PTFE Toxicosis Detail", "Avian Teflon Fume Fever",
      "Avian Avocado Toxicosis",
      "Avian Liver Disease Detail", "Avian Hepatic Lipidosis",
      "Avian Hemochromatosis",
      "Avian Renal Disease Detail", "Avian Renal Tumor",
      "Avian Atherosclerosis Detail", "Avian Aortic Atherosclerosis",
      "Avian Crop Stasis Detail", "Avian Crop Impaction",
      "Avian Crop Fistula", "Avian Crop Foreign Body",
      "Avian Knemidocoptes Mange", "Avian Scaly Face Mite",
      "Avian Scaly Leg Mite", "Avian Red Mite",
      "Avian Feather Lice", "Avian Air Sac Mite",
      "Avian Bacterial Sinusitis", "Avian Upper Respiratory Infection",
      "Avian Psittacine Papillomavirus",
      "Avian Pacheco Disease", "Avian Herpesvirus",
      "Avian Newcastle Disease",
      "Avian Wing Fracture", "Avian Leg Fracture",
      "Avian Keel Fracture", "Avian Bumblefoot Detail",
      "Avian Constricted Toe Syndrome",
      "Avian Malnutrition Seed Diet", "Avian Pellet Conversion",
      "Avian Vitamin A Deficiency Detail",
    ],
    // ═══ WAVE 2: DENTAL EXPANDED ═══
    dental_w2: [
      "Periodontal Disease Stage 1", "Periodontal Disease Stage 2",
      "Periodontal Disease Stage 3", "Periodontal Disease Stage 4",
      "Tooth Resorption Type 1", "Tooth Resorption Type 2",
      "Tooth Resorption Type 3",
      "Complicated Crown Fracture", "Uncomplicated Crown Fracture",
      "Root Fracture", "Crown Root Fracture",
      "Dental Trauma Avulsion", "Dental Trauma Luxation",
      "Dental Trauma Intrusion",
      "Tooth Root Abscess Detail", "Carnassial Tooth Abscess",
      "Infraorbital Swelling Dental",
      "Oronasal Fistula Detail", "Palatal Defect Repair",
      "Mandibular Fracture Dental Detail", "Symphyseal Separation",
      "Maxillary Fracture", "TMJ Luxation",
      "TMJ Dysplasia", "TMJ Ankylosis",
      "Open Mouth Jaw Locking", "Closed Mouth Jaw Locking",
      "Gingival Hyperplasia Detail", "Gingival Recession",
      "Gingival Squamous Cell Carcinoma",
      "Oral Fibrosarcoma Detail", "Oral Papilloma Detail",
      "Canine Chronic Ulcerative Stomatitis",
      "Feline Chronic Gingivostomatitis Detail",
      "Feline Caudal Stomatitis", "Feline Full Mouth Extraction",
      "Odontogenic Cyst", "Radicular Cyst",
      "Enamel Hypoplasia Detail", "Enamel Hypomineralization",
      "Dental Prophylaxis Protocol",
      "Dental Radiography Technique",
      "Regional Nerve Block Dental",
    ],
    // ═══ WAVE 2: SURGICAL / ANESTHESIA ═══
    surgery_w2: [
      "Ovariohysterectomy Complications", "Ovariectomy",
      "Castration Complications", "Cryptorchid Surgery",
      "Cesarean Section Canine", "Cesarean Section Feline",
      "Mastectomy Chain Mammary", "Regional Mastectomy",
      "Splenectomy Indications Detail", "Partial Splenectomy",
      "Liver Biopsy Technique", "Kidney Biopsy Technique",
      "Lymph Node Biopsy", "Bone Marrow Biopsy",
      "Fine Needle Aspirate Technique",
      "Chest Tube Management", "Thoracoscopy",
      "Laparoscopy Veterinary", "Arthroscopy Veterinary",
      "Endoscopy GI", "Bronchoscopy",
      "Rhinoscopy", "Cystoscopy",
      "Otoscopy Video", "Wound Debridement",
      "Wound Vacuum Therapy", "Wound Healing Phases",
      "Surgical Site Infection", "Surgical Drain Management",
      "Anesthesia Premedication", "Anesthesia Induction",
      "Anesthesia Maintenance", "Anesthesia Recovery",
      "Anesthesia Complications", "Anesthetic Emergency",
      "Local Anesthesia Technique", "Epidural Anesthesia",
      "Nerve Block Technique", "Analgesia Protocols",
      "Sedation Protocols", "High Risk Patient Anesthesia",
      "Brachycephalic Anesthesia", "Pediatric Anesthesia",
      "Geriatric Anesthesia", "Cardiac Patient Anesthesia",
    ],
    // ═══ WAVE 2: PREVENTIVE / WELLNESS ═══
    preventive_w2: [
      "Vaccination Protocol Canine Core",
      "Vaccination Protocol Canine Non-Core",
      "Vaccination Protocol Feline Core",
      "Vaccination Protocol Feline Non-Core",
      "Vaccination Protocol Rabbit",
      "Vaccination Protocol Ferret",
      "Vaccine Adverse Reaction", "Vaccine Failure",
      "Puppy Wellness Protocol", "Kitten Wellness Protocol",
      "Adult Dog Wellness", "Adult Cat Wellness",
      "Senior Dog Wellness", "Senior Cat Wellness",
      "Geriatric Screening Panel",
      "Flea Prevention Protocol", "Tick Prevention Protocol",
      "Heartworm Prevention Protocol",
      "Intestinal Parasite Prevention", "Deworming Protocol",
      "Dental Prophylaxis Importance",
      "Nutrition Assessment Canine", "Nutrition Assessment Feline",
      "Body Condition Score System",
      "Obesity Prevention Program",
      "Microchip Identification",
      "Spay Neuter Benefits Risks",
      "Pre-Anesthetic Screening",
      "Travel Health Certificate",
      "Quarantine Requirements",
      "Zoonotic Disease Awareness",
    ],
    // ═══ WAVE 2: DIAGNOSTIC IMAGING / LABORATORY ═══
    diagnostic_w2: [
      "Radiographic Interpretation Thorax", "Radiographic Interpretation Abdomen",
      "Radiographic Interpretation Skeletal",
      "Abdominal Ultrasound Interpretation", "Cardiac Ultrasound Echocardiography",
      "Doppler Ultrasound Veterinary",
      "CT Scan Veterinary Applications", "MRI Veterinary Applications",
      "Nuclear Scintigraphy Thyroid", "Nuclear Scintigraphy Bone",
      "Fluoroscopy Veterinary",
      "CBC Interpretation Canine", "CBC Interpretation Feline",
      "Blood Chemistry Panel Interpretation",
      "Urinalysis Interpretation", "Urine Culture Interpretation",
      "Coagulation Panel Interpretation",
      "Blood Gas Analysis", "Electrolyte Panel Interpretation",
      "Cytology Interpretation", "Histopathology Interpretation",
      "Bone Marrow Evaluation",
      "Endocrine Testing Protocols",
      "Thyroid Panel Interpretation", "Cortisol Testing Protocol",
      "ACTH Stimulation Test", "Low Dose Dexamethasone Suppression",
      "High Dose Dexamethasone Suppression",
      "Fructosamine Interpretation", "Glucose Curve Interpretation",
      "Coombs Test", "ANA Test",
      "Infectious Disease PCR Testing",
      "Serology Interpretation", "Titer Testing Vaccination",
      "Point of Care Testing", "SNAP Test Interpretation",
    ],
    // ═══ WAVE 2: NEONATAL / PEDIATRIC ═══
    neonatal_w2: [
      "Neonatal Puppy Care", "Neonatal Kitten Care",
      "Neonatal Resuscitation", "Neonatal Assessment",
      "Fading Puppy Syndrome Detail", "Fading Kitten Syndrome Detail",
      "Neonatal Isoerythrolysis Detail Neonatal",
      "Neonatal Septicemia", "Neonatal Hypothermia",
      "Neonatal Hypoglycemia", "Neonatal Dehydration",
      "Neonatal Umbilical Infection", "Neonatal Toxic Milk Syndrome",
      "Orphan Puppy Rearing", "Orphan Kitten Rearing",
      "Bottle Feeding Complications",
      "Cleft Palate Neonatal Management",
      "Congenital Heart Disease Neonatal",
      "Swimmer Puppy Syndrome", "Flat Chested Kitten Syndrome",
      "Juvenile Hypoglycemia", "Juvenile Cellulitis Detail",
      "Puppy Strangles",
      "Pediatric Vaccination Schedule",
      "Pediatric Deworming Protocol",
      "Pediatric Spay Neuter Timing",
      "Growth Plate Injury Pediatric",
      "Retained Deciduous Teeth",
      "Juvenile Polyarthritis",
      "Juvenile Onset Diabetes",
    ],
    // ═══ WAVE 2: NUTRITION / METABOLIC EXPANDED ═══
    nutrition_w2: [
      "Raw Diet Benefits Risks", "Grain Free Diet Controversy",
      "Diet Associated Dilated Cardiomyopathy",
      "Novel Protein Diet", "Hydrolyzed Protein Diet",
      "Prescription Diet Renal", "Prescription Diet Hepatic",
      "Prescription Diet Diabetic", "Prescription Diet Weight Loss",
      "Prescription Diet GI", "Prescription Diet Urinary",
      "Prescription Diet Hypoallergenic",
      "Home Cooked Diet Formulation",
      "BARF Diet Veterinary Perspective",
      "Vegetarian Vegan Diet Dogs",
      "Feeding Tube Management", "Esophagostomy Tube",
      "Gastrostomy Tube PEG", "Nasogastric Tube",
      "Nasoesophageal Tube",
      "Total Parenteral Nutrition Veterinary",
      "Partial Parenteral Nutrition",
      "Enteral Feeding Protocol",
      "Caloric Requirement Calculation",
      "Resting Energy Requirement",
      "Illness Energy Requirement",
      "Protein Requirements Critical Illness",
      "Omega 3 Fatty Acid Supplementation",
      "Glucosamine Chondroitin Supplementation",
      "Probiotics Veterinary Use",
      "Prebiotics Veterinary Use",
      "Fiber Supplementation",
      "Antioxidant Supplementation",
    ],
  };
}

// ─── Main ─────────────────────────────────────────────
async function main() {
  console.log("=== VetPro Disease Master List Builder ===\n");

  // 1. Extract from Merck sections
  console.log("1. Extracting Merck Manual section titles...");
  const merckDiseases = extractMerckDiseases();
  console.log(`   Found ${merckDiseases.length} Merck sections with content\n`);

  // 2. Load curated taxonomy
  console.log("2. Loading curated veterinary disease taxonomy...");
  const curated = getCuratedDiseases();
  let curatedTotal = 0;
  const curatedFlat: string[] = [];
  for (const [category, diseases] of Object.entries(curated)) {
    console.log(`   ${category}: ${diseases.length} diseases`);
    curatedTotal += diseases.length;
    curatedFlat.push(...diseases);
  }
  console.log(`   Total curated: ${curatedTotal}\n`);

  // 3. Combine all sources
  const allCandidates = {
    merckSections: merckDiseases,
    curatedByCategory: curated,
    curatedFlat: [...new Set(curatedFlat)],
    totalMerck: merckDiseases.length,
    totalCurated: curatedTotal,
    totalUniqueCurated: new Set(curatedFlat).size,
    generatedAt: new Date().toISOString(),
  };

  // 4. Write output
  fs.writeFileSync(OUTPUT_FILE, JSON.stringify(allCandidates, null, 2), "utf-8");
  console.log(`Output written to: ${OUTPUT_FILE}`);
  console.log(`Total unique curated diseases: ${allCandidates.totalUniqueCurated}`);
  console.log(`Total Merck sections: ${allCandidates.totalMerck}`);
}

main().catch(err => {
  console.error("Fatal error:", err);
  process.exit(1);
});
