/**
 * disease-master-list.ts
 *
 * Collect comprehensive veterinary disease candidates from multiple sources:
 * 1. Merck Veterinary Manual section titles (11,526 sections)
 * 2. Curated veterinary disease taxonomy (organized by specialty)
 * 3. MeSH terms via NCBI E-utilities
 *
 * Output: scripts/disease-candidates.json
 */
import fs from "fs";
import path from "path";

const MERCK_SECTIONS_DIR = "C:/project/merck-sections";
const OUTPUT_FILE = path.join(process.cwd(), "scripts", "disease-candidates.json");

// ─── Merck Section Extraction ─────────────────────────
function extractMerckDiseases(): string[] {
  const indexPath = path.join(MERCK_SECTIONS_DIR, "index.json");
  if (!fs.existsSync(indexPath)) {
    console.warn("Merck sections index not found, skipping");
    return [];
  }

  const index = JSON.parse(fs.readFileSync(indexPath, "utf-8"));
  const diseases: string[] = [];

  // Filter for disease-like section titles
  const skipPatterns = [
    /^(INTRODUCTION|OVERVIEW|TABLE|FIGURE|CHAPTER|INDEX|APPENDIX)/i,
    /^(THE |GENERAL |PRINCIPLES OF |APPROACH TO)/i,
    /\d{3,}/, // Page numbers only
    /^[A-Z\s]{1,5}$/, // Too short (likely chapter codes)
  ];

  for (const [chapterCode, chapterData] of Object.entries(index) as [string, any][]) {
    for (const section of chapterData.sections) {
      const title = section.title.replace(/\s+\d+$/, "").trim(); // Remove trailing page numbers
      if (title.length < 5) continue;
      if (skipPatterns.some(p => p.test(title))) continue;
      if (section.text_length > 200) { // Only sections with meaningful content
        diseases.push(title);
      }
    }
  }

  return [...new Set(diseases)];
}

// ─── Curated Veterinary Disease Taxonomy ──────────────
// Comprehensive list organized by veterinary specialty
// This covers the ~2,500+ diseases we aim to include
function getCuratedDiseases(): Record<string, string[]> {
  return {
    // ═══ CARDIOLOGY / CIRCULATORY ═══
    cardiac: [
      // Congenital heart disease
      "Ventricular Septal Defect", "Atrial Septal Defect", "Patent Ductus Arteriosus",
      "Tetralogy of Fallot", "Pulmonic Stenosis", "Subaortic Stenosis",
      "Aortic Stenosis", "Tricuspid Valve Dysplasia", "Mitral Valve Dysplasia",
      "Persistent Right Aortic Arch", "Cor Triatriatum", "Endocardial Fibroelastosis",
      "Eisenmenger Syndrome", "Double Outlet Right Ventricle",
      // Acquired heart disease
      "Myxomatous Mitral Valve Disease", "Dilated Cardiomyopathy",
      "Hypertrophic Cardiomyopathy", "Restrictive Cardiomyopathy",
      "Arrhythmogenic Right Ventricular Cardiomyopathy",
      "Infective Endocarditis", "Pericardial Effusion", "Cardiac Tamponade",
      "Congestive Heart Failure", "Atrial Fibrillation",
      "Ventricular Tachycardia", "Supraventricular Tachycardia",
      "Sick Sinus Syndrome", "Atrioventricular Block",
      "Third Degree Heart Block", "Bundle Branch Block",
      "Pulmonary Hypertension", "Pulmonary Thromboembolism",
      "Aortic Thromboembolism", "Heartworm Disease",
      "Systemic Hypertension", "Boxer Cardiomyopathy",
      "Doberman Cardiomyopathy", "Cavalier King Charles Spaniel MVD",
      "Myocarditis", "Pericarditis", "Cardiac Hemangiosarcoma",
      "Cardiac Lymphoma", "Chemodectoma",
    ],
    // ═══ HEMATOLOGY ═══
    hematology: [
      "Immune-Mediated Hemolytic Anemia", "Immune-Mediated Thrombocytopenia",
      "Evans Syndrome", "Non-Regenerative Anemia", "Aplastic Anemia",
      "Pure Red Cell Aplasia", "Iron Deficiency Anemia",
      "Hemolytic Anemia", "Methemoglobinemia", "Heinz Body Anemia",
      "Zinc Toxicosis Hemolytic Anemia", "Babesiosis",
      "Disseminated Intravascular Coagulation", "Von Willebrand Disease",
      "Hemophilia A", "Hemophilia B", "Factor VII Deficiency",
      "Thrombocytopenia", "Thrombocytosis", "Neutropenia",
      "Neutrophilia", "Eosinophilia", "Lymphocytosis",
      "Pancytopenia", "Polycythemia", "Polycythemia Vera",
      "Erythrocytosis", "Leukemia", "Acute Lymphoblastic Leukemia",
      "Chronic Lymphocytic Leukemia", "Acute Myeloid Leukemia",
      "Myelodysplastic Syndrome", "Multiple Myeloma",
      "Transfusion Reactions", "Blood Type Incompatibility",
      "Neonatal Isoerythrolysis", "Coagulopathy",
      "Hypercoagulability", "Histiocytic Sarcoma",
      "Hemophagocytic Syndrome", "Systemic Histiocytosis",
    ],
    // ═══ RESPIRATORY ═══
    respiratory: [
      "Brachycephalic Airway Syndrome", "Laryngeal Paralysis",
      "Tracheal Collapse", "Tracheal Hypoplasia",
      "Kennel Cough", "Canine Infectious Respiratory Disease Complex",
      "Feline Upper Respiratory Infection", "Feline Herpesvirus Rhinitis",
      "Feline Calicivirus Infection", "Chronic Rhinitis",
      "Nasal Aspergillosis", "Nasal Foreign Body",
      "Nasal Tumor", "Nasopharyngeal Polyp", "Nasopharyngeal Stenosis",
      "Pneumonia", "Aspiration Pneumonia", "Fungal Pneumonia",
      "Bacterial Pneumonia", "Viral Pneumonia",
      "Eosinophilic Bronchopneumopathy", "Feline Asthma",
      "Chronic Bronchitis", "Bronchiectasis",
      "Pulmonary Edema", "Pulmonary Fibrosis",
      "Pulmonary Contusion", "Pulmonary Abscess",
      "Lung Lobe Torsion", "Primary Lung Tumor",
      "Pulmonary Metastasis", "Pleural Effusion",
      "Chylothorax", "Pyothorax", "Hemothorax",
      "Pneumothorax", "Tension Pneumothorax",
      "Diaphragmatic Hernia", "Peritoneopericardial Diaphragmatic Hernia",
      "Mediastinal Mass", "Thymoma",
      "Acute Respiratory Distress Syndrome",
      "Smoke Inhalation Injury", "Near Drowning",
      "Tracheal Avulsion", "Epiglottic Retroversion",
      "Subglottic Stenosis", "Tracheal Tear",
    ],
    // ═══ GASTROINTESTINAL ═══
    gastrointestinal: [
      "Megaesophagus", "Esophageal Stricture", "Esophageal Foreign Body",
      "Esophagitis", "Hiatal Hernia", "Vascular Ring Anomaly",
      "Gastric Dilatation Volvulus", "Gastric Foreign Body",
      "Gastric Ulcer", "Gastritis", "Chronic Gastritis",
      "Helicobacter Gastritis", "Gastroparesis",
      "Pyloric Stenosis", "Gastric Neoplasia",
      "Intestinal Foreign Body", "Intestinal Intussusception",
      "Intestinal Volvulus", "Mesenteric Torsion",
      "Small Intestinal Bacterial Overgrowth",
      "Inflammatory Bowel Disease", "Lymphocytic Plasmacytic Enteritis",
      "Eosinophilic Enteritis", "Granulomatous Enteritis",
      "Protein Losing Enteropathy", "Intestinal Lymphangiectasia",
      "Chronic Enteropathy", "Food Responsive Enteropathy",
      "Antibiotic Responsive Enteropathy",
      "Colitis", "Histiocytic Ulcerative Colitis",
      "Fiber Responsive Colitis", "Irritable Bowel Syndrome",
      "Constipation", "Megacolon", "Obstipation",
      "Rectal Prolapse", "Perianal Fistula",
      "Anal Sac Disease", "Anal Sac Adenocarcinoma",
      "Intestinal Lymphoma", "Intestinal Adenocarcinoma",
      "Intestinal Leiomyoma", "Intestinal Leiomyosarcoma",
      "Gastrointestinal Stromal Tumor",
      "Pancreatitis", "Acute Pancreatitis", "Chronic Pancreatitis",
      "Exocrine Pancreatic Insufficiency", "Pancreatic Abscess",
      "Pancreatic Neoplasia", "Insulinoma",
      "Parvoviral Enteritis", "Canine Coronavirus Enteritis",
      "Salmonellosis", "Campylobacteriosis",
      "Clostridium Difficile Infection", "Clostridium Perfringens Enterotoxicosis",
      "Tritrichomonas Foetus", "Giardiasis", "Coccidia Infection",
      "Hemorrhagic Gastroenteritis", "Short Bowel Syndrome",
      "Ileus", "Peritonitis", "Bile Peritonitis",
      "Salivary Mucocele", "Sialocele",
      "Oral Melanoma", "Squamous Cell Carcinoma of the Oral Cavity",
      "Oral Fibrosarcoma", "Epulis", "Gingival Hyperplasia",
      "Stomatitis", "Feline Chronic Gingivostomatitis",
    ],
    // ═══ HEPATIC / LIVER ═══
    hepatic: [
      "Chronic Hepatitis", "Acute Hepatic Failure",
      "Hepatic Lipidosis", "Copper Hepatopathy",
      "Cholangitis", "Cholangiohepatitis",
      "Triaditis", "Biliary Obstruction",
      "Gallbladder Mucocele", "Cholelithiasis",
      "Portosystemic Shunt", "Congenital Portosystemic Shunt",
      "Acquired Portosystemic Shunt",
      "Hepatic Encephalopathy", "Hepatic Fibrosis",
      "Cirrhosis", "Hepatic Abscess",
      "Hepatocellular Carcinoma", "Hepatic Lymphoma",
      "Biliary Carcinoma", "Cholecystitis",
      "Vacuolar Hepatopathy", "Drug-Induced Hepatotoxicity",
      "Lobular Dissecting Hepatitis",
      "Hepatocutaneous Syndrome", "Nodular Hyperplasia of the Liver",
      "Hepatic Amyloidosis",
    ],
    // ═══ URINARY / RENAL ═══
    urinary: [
      "Chronic Kidney Disease", "Acute Kidney Injury",
      "Glomerulonephritis", "Protein Losing Nephropathy",
      "Amyloidosis Renal", "Polycystic Kidney Disease",
      "Renal Dysplasia", "Pyelonephritis",
      "Urolithiasis", "Calcium Oxalate Urolithiasis",
      "Struvite Urolithiasis", "Urate Urolithiasis",
      "Cystine Urolithiasis", "Silica Urolithiasis",
      "Feline Lower Urinary Tract Disease", "Feline Idiopathic Cystitis",
      "Urethral Obstruction", "Urinary Tract Infection",
      "Ectopic Ureter", "Urinary Incontinence",
      "Urethral Prolapse", "Urethral Stricture",
      "Bladder Neoplasia", "Transitional Cell Carcinoma",
      "Renal Lymphoma", "Renal Cell Carcinoma",
      "Nephroblastoma", "Hydronephrosis",
      "Renal Tubular Acidosis", "Fanconi Syndrome",
      "Juvenile Nephropathy", "Familial Nephropathy",
      "Nephrotic Syndrome", "Peritoneal Dialysis Complications",
    ],
    // ═══ ENDOCRINE ═══
    endocrine: [
      "Diabetes Mellitus", "Diabetic Ketoacidosis",
      "Diabetic Neuropathy", "Somogyi Effect",
      "Hypoglycemia", "Insulinoma",
      "Hyperadrenocorticism", "Pituitary Dependent Hyperadrenocorticism",
      "Adrenal Dependent Hyperadrenocorticism", "Iatrogenic Hyperadrenocorticism",
      "Hypoadrenocorticism", "Atypical Hypoadrenocorticism",
      "Hypothyroidism", "Congenital Hypothyroidism",
      "Hyperthyroidism", "Thyroid Carcinoma",
      "Hyperparathyroidism", "Primary Hyperparathyroidism",
      "Secondary Renal Hyperparathyroidism", "Nutritional Hyperparathyroidism",
      "Hypoparathyroidism",
      "Pheochromocytoma", "Aldosterone Secreting Tumor",
      "Adrenocortical Carcinoma",
      "Acromegaly", "Pituitary Dwarfism", "Diabetes Insipidus",
      "Central Diabetes Insipidus", "Nephrogenic Diabetes Insipidus",
      "Syndrome of Inappropriate Antidiuretic Hormone",
      "Hyperaldosteronism", "Ferret Adrenal Disease",
    ],
    // ═══ NEUROLOGY ═══
    neurology: [
      "Intervertebral Disc Disease", "Cervical Disc Disease",
      "Thoracolumbar Disc Disease", "Fibrocartilaginous Embolism",
      "Degenerative Myelopathy", "Cervical Spondylomyelopathy",
      "Atlantoaxial Instability", "Cauda Equina Syndrome",
      "Lumbosacral Stenosis", "Syringomyelia",
      "Chiari-Like Malformation", "Spinal Cord Tumor",
      "Meningioma", "Glioma", "Choroid Plexus Tumor",
      "Brain Tumor", "Pituitary Macroadenoma",
      "Idiopathic Epilepsy", "Structural Epilepsy",
      "Status Epilepticus", "Cluster Seizures",
      "Meningitis", "Meningoencephalitis of Unknown Origin",
      "Granulomatous Meningoencephalitis",
      "Necrotizing Encephalitis", "Necrotizing Leukoencephalitis",
      "Steroid Responsive Meningitis Arteritis",
      "Canine Distemper Encephalitis", "Feline Infectious Peritonitis Neurologic",
      "Toxoplasma Encephalitis", "Neosporosis",
      "Rabies", "Vestibular Disease", "Peripheral Vestibular Disease",
      "Central Vestibular Disease", "Idiopathic Vestibular Syndrome",
      "Facial Nerve Paralysis", "Trigeminal Neuritis",
      "Horner Syndrome", "Brachial Plexus Avulsion",
      "Polyradiculoneuritis", "Coonhound Paralysis",
      "Myasthenia Gravis", "Acquired Myasthenia Gravis",
      "Congenital Myasthenia Gravis",
      "Tetanus", "Botulism",
      "Cognitive Dysfunction Syndrome",
      "Hydrocephalus", "Cerebellar Hypoplasia",
      "Cerebellar Abiotrophy", "Lissencephaly",
      "Spinal Dysraphism", "Hemivertebra",
      "Polymyositis", "Masticatory Muscle Myositis",
      "Extraocular Myositis", "Muscular Dystrophy",
      "Narcolepsy", "Scotty Cramp",
      "Dancing Doberman Disease", "Sensory Neuropathy",
      "Metabolic Encephalopathy", "Hepatic Encephalopathy Neurologic",
      "Uremic Encephalopathy",
    ],
    // ═══ OPHTHALMOLOGY ═══
    ophthalmology: [
      "Corneal Ulcer", "Indolent Ulcer", "Melting Ulcer",
      "Corneal Sequestrum", "Keratoconjunctivitis Sicca",
      "Conjunctivitis", "Allergic Conjunctivitis",
      "Cherry Eye", "Entropion", "Ectropion",
      "Distichiasis", "Ectopic Cilia", "Trichiasis",
      "Cataracts", "Lens Luxation", "Nuclear Sclerosis",
      "Glaucoma", "Primary Glaucoma", "Secondary Glaucoma",
      "Anterior Uveitis", "Posterior Uveitis", "Panuveitis",
      "Lens Induced Uveitis", "Traumatic Uveitis",
      "Progressive Retinal Atrophy", "Sudden Acquired Retinal Degeneration",
      "Retinal Detachment", "Retinal Hemorrhage",
      "Collie Eye Anomaly", "Persistent Pupillary Membranes",
      "Persistent Hyperplastic Primary Vitreous",
      "Iris Melanosis", "Iris Melanoma", "Uveal Melanoma",
      "Orbital Neoplasia", "Retrobulbar Abscess",
      "Proptosis", "Hyphema", "Corneal Dystrophy",
      "Corneal Degeneration", "Lipid Keratopathy",
      "Pannus", "Chronic Superficial Keratitis",
      "Feline Eosinophilic Keratitis", "Symblepharon",
      "Blepharitis", "Meibomian Gland Dysfunction",
      "Epiphora", "Nasolacrimal Duct Obstruction",
      "Canine Multifocal Retinopathy", "Optic Neuritis",
      "Phacoclastic Uveitis",
    ],
    // ═══ EAR ═══
    ear: [
      "Otitis Externa", "Otitis Media", "Otitis Interna",
      "Aural Hematoma", "Ear Mites", "Nasopharyngeal Polyp",
      "Deafness", "Congenital Deafness",
      "Ear Canal Tumor", "Ceruminous Gland Adenocarcinoma",
      "Total Ear Canal Ablation", "Lateral Ear Resection",
      "Ear Margin Dermatosis", "Pinnal Vasculitis",
    ],
    // ═══ DERMATOLOGY ═══
    dermatology: [
      "Atopic Dermatitis", "Food Allergy Dermatitis",
      "Flea Allergy Dermatitis", "Contact Dermatitis",
      "Pyoderma", "Superficial Pyoderma", "Deep Pyoderma",
      "Methicillin Resistant Staphylococcus", "Skin Fold Dermatitis",
      "Demodicosis", "Generalized Demodicosis", "Localized Demodicosis",
      "Sarcoptic Mange", "Notoedric Mange",
      "Cheyletiellosis", "Dermatophytosis", "Malassezia Dermatitis",
      "Hot Spot", "Acral Lick Dermatitis",
      "Pemphigus Foliaceus", "Pemphigus Vulgaris",
      "Bullous Pemphigoid", "Discoid Lupus Erythematosus",
      "Systemic Lupus Erythematosus", "Vasculitis",
      "Erythema Multiforme", "Toxic Epidermal Necrolysis",
      "Drug Eruption", "Sebaceous Adenitis",
      "Alopecia X", "Pattern Baldness",
      "Color Dilution Alopecia", "Seasonal Flank Alopecia",
      "Dermoid Sinus", "Calcinosis Cutis",
      "Cutaneous Lymphoma", "Mast Cell Tumor",
      "Soft Tissue Sarcoma", "Fibrosarcoma",
      "Squamous Cell Carcinoma Cutaneous", "Melanoma Cutaneous",
      "Histiocytoma", "Lipoma", "Liposarcoma",
      "Sebaceous Gland Tumor", "Perianal Gland Tumor",
      "Trichoepithelioma", "Pilomatricoma",
      "Basal Cell Tumor", "Hemangiopericytoma",
      "Subcutaneous Hemangiosarcoma",
      "Acanthomatous Ameloblastoma",
      "Digital Squamous Cell Carcinoma",
      "Nail Bed Tumor", "Subungual Melanoma",
      "Panniculitis", "Sterile Nodular Panniculitis",
      "Juvenile Cellulitis", "Canine Acne",
      "Zinc Responsive Dermatosis", "Vitamin A Responsive Dermatosis",
      "Hypothyroid Dermatosis", "Hyperadrenocorticism Dermatosis",
      "Shar-Pei Fever", "Shar-Pei Amyloidosis",
      "Callus Dermatitis", "Pressure Sore",
      "Fly Strike Dermatitis",
    ],
    // ═══ ORTHOPEDIC / MUSCULOSKELETAL ═══
    orthopedic: [
      "Cranial Cruciate Ligament Rupture", "Medial Patellar Luxation",
      "Lateral Patellar Luxation", "Hip Dysplasia",
      "Elbow Dysplasia", "Fragmented Coronoid Process",
      "Ununited Anconeal Process", "Osteochondritis Dissecans",
      "Legg Calve Perthes Disease", "Aseptic Necrosis Femoral Head",
      "Fracture Management", "Radius Ulna Fracture",
      "Femoral Fracture", "Tibial Fracture",
      "Humeral Fracture", "Pelvic Fracture",
      "Spinal Fracture", "Mandibular Fracture",
      "Growth Plate Fracture", "Pathologic Fracture",
      "Angular Limb Deformity", "Premature Physeal Closure",
      "Panosteitis", "Hypertrophic Osteodystrophy",
      "Hypertrophic Osteopathy",
      "Osteosarcoma", "Chondrosarcoma", "Synovial Sarcoma",
      "Multilobular Osteochondrosarcoma",
      "Osteomyelitis", "Septic Arthritis",
      "Immune-Mediated Polyarthritis", "Rheumatoid Arthritis",
      "Polyarthritis", "Osteoarthritis",
      "Muscle Strain", "Tendon Injury",
      "Biceps Tendinopathy", "Supraspinatus Tendinopathy",
      "Infraspinatus Contracture", "Gracilis Contracture",
      "Fibrotic Myopathy", "Achilles Tendon Rupture",
      "Carpal Hyperextension", "Tarsal Instability",
      "Shoulder Luxation", "Hip Luxation",
      "Temporomandibular Joint Luxation",
      "Coxofemoral Luxation",
      "Scottish Fold Osteochondrodysplasia",
      "Mucopolysaccharidosis", "Glycogen Storage Disease",
    ],
    // ═══ DENTAL ═══
    dental: [
      "Periodontal Disease", "Tooth Resorption",
      "Feline Odontoclastic Resorptive Lesion",
      "Tooth Fracture", "Dental Abscess",
      "Malocclusion", "Mandibular Prognathism",
      "Maxillary Brachygnathism", "Deciduous Tooth Retention",
      "Supernumerary Teeth", "Missing Teeth",
      "Enamel Hypoplasia", "Tooth Discoloration",
      "Mandibular Osteomyelitis", "Oronasal Fistula",
      "Jaw Fracture Dental", "Dentigerous Cyst",
      "Ameloblastoma", "Oral Papilloma",
    ],
    // ═══ ONCOLOGY ═══
    oncology: [
      "Lymphoma", "Multicentric Lymphoma", "Mediastinal Lymphoma",
      "Alimentary Lymphoma", "Cutaneous Lymphoma",
      "Hepatosplenic Lymphoma", "Large Granular Lymphocyte Lymphoma",
      "Mast Cell Tumor", "Hemangiosarcoma", "Splenic Hemangiosarcoma",
      "Osteosarcoma", "Soft Tissue Sarcoma",
      "Fibrosarcoma", "Injection Site Sarcoma",
      "Melanoma", "Oral Melanoma",
      "Squamous Cell Carcinoma", "Nasal Tumor",
      "Thyroid Carcinoma", "Mammary Tumor",
      "Mammary Adenocarcinoma", "Ovarian Tumor",
      "Testicular Tumor", "Sertoli Cell Tumor",
      "Seminoma", "Leydig Cell Tumor",
      "Prostate Carcinoma", "Prostatic Adenocarcinoma",
      "Transitional Cell Carcinoma", "Bladder Tumor",
      "Brain Tumor Oncology", "Meningioma Oncology",
      "Pituitary Tumor", "Adrenal Tumor",
      "Hepatocellular Carcinoma Oncology", "Bile Duct Carcinoma",
      "Pancreatic Carcinoma", "Anal Sac Adenocarcinoma Oncology",
      "Apocrine Gland Carcinoma", "Perianal Adenoma",
      "Lung Carcinoma", "Pulmonary Adenocarcinoma",
      "Cardiac Tumor", "Chemodectoma Oncology",
      "Thymoma Oncology", "Ectopic Thyroid Carcinoma",
      "Multiple Endocrine Neoplasia",
      "Paraneoplastic Syndrome", "Hypercalcemia of Malignancy",
      "Cancer Associated Cachexia",
      "Chondrosarcoma Oncology", "Osteochondroma",
      "Vaccine Associated Sarcoma",
      "Feline Mammary Carcinoma",
      "Canine Histiocytic Sarcoma",
      "Hemangiopericytoma Oncology", "Liposarcoma Oncology",
      "Peripheral Nerve Sheath Tumor",
      "Gastrointestinal Stromal Tumor Oncology",
      "Intestinal Adenocarcinoma Oncology",
      "Splenic Tumor", "Splenic Mass",
    ],
    // ═══ INFECTIOUS DISEASE ═══
    infectious: [
      // Viral
      "Canine Parvovirus", "Canine Distemper",
      "Canine Infectious Hepatitis", "Canine Coronavirus",
      "Canine Influenza", "Canine Herpesvirus",
      "Canine Papillomatosis",
      "Feline Panleukopenia", "Feline Herpesvirus",
      "Feline Calicivirus", "Feline Leukemia Virus",
      "Feline Immunodeficiency Virus", "Feline Infectious Peritonitis",
      "Feline Coronavirus",
      "Rabies",
      // Bacterial
      "Leptospirosis", "Brucellosis", "Bartonellosis",
      "Borreliosis", "Lyme Disease",
      "Ehrlichiosis", "Anaplasmosis",
      "Rocky Mountain Spotted Fever", "Rickettsiosis",
      "Nocardiosis", "Actinomycosis",
      "Mycobacterial Infection", "Tularemia",
      "Plague", "Salmonellosis Infectious",
      "Campylobacteriosis Infectious",
      "Listeriosis", "Leptospirosis Systemic",
      "Bordetella Bronchiseptica", "Tetanus Infectious",
      "Clostridial Infection",
      "Streptococcal Infection", "Staphylococcal Infection",
      "Pseudomonas Infection", "E Coli Infection",
      // Fungal
      "Blastomycosis", "Histoplasmosis",
      "Coccidioidomycosis", "Cryptococcosis",
      "Aspergillosis", "Sporotrichosis",
      "Dermatophytosis Infectious", "Pythiosis",
      "Lagenidiosis", "Protothecosis",
      // Protozoal
      "Babesiosis", "Cytauxzoonosis",
      "Hepatozoonosis", "Leishmaniasis",
      "Toxoplasmosis", "Neosporosis Infectious",
      "Giardiasis Infectious", "Coccidiosis",
      "Trypanosomiasis", "Tritrichomonas",
      // Parasitic
      "Heartworm Disease Infectious", "Toxocariasis",
      "Hookworm Infection", "Whipworm Infection",
      "Tapeworm Infection", "Lungworm Infection",
      "Angiostrongylosis", "Dirofilariasis",
      "Strongyloides", "Filaroides",
      "Cuterebra", "Myiasis",
      "Demodex Infectious", "Sarcoptes Infectious",
    ],
    // ═══ TOXICOLOGY ═══
    toxicology: [
      "Chocolate Toxicosis", "Xylitol Toxicosis",
      "Grape and Raisin Toxicosis", "Onion and Garlic Toxicosis",
      "Macadamia Nut Toxicosis", "Avocado Toxicosis",
      "Alcohol Toxicosis", "Caffeine Toxicosis",
      "Ethylene Glycol Toxicosis", "Antifreeze Poisoning",
      "Anticoagulant Rodenticide Toxicosis", "Bromethalin Toxicosis",
      "Cholecalciferol Rodenticide Toxicosis", "Zinc Phosphide Toxicosis",
      "Strychnine Toxicosis",
      "Organophosphate Toxicosis", "Pyrethrin Pyrethroid Toxicosis",
      "Permethrin Toxicosis in Cats", "Ivermectin Toxicosis",
      "Metaldehyde Toxicosis", "Snail Bait Toxicosis",
      "Acetaminophen Toxicosis", "NSAID Toxicosis",
      "Ibuprofen Toxicosis", "Naproxen Toxicosis",
      "Aspirin Toxicosis", "Corticosteroid Overdose",
      "Lead Toxicosis", "Zinc Toxicosis",
      "Copper Toxicosis", "Iron Toxicosis",
      "Arsenic Toxicosis", "Mercury Toxicosis",
      "Lily Toxicosis", "Sago Palm Toxicosis",
      "Oleander Toxicosis", "Autumn Crocus Toxicosis",
      "Castor Bean Toxicosis", "Marijuana Toxicosis",
      "Cannabis Toxicosis", "Mushroom Toxicosis",
      "Blue-Green Algae Toxicosis", "Cyanobacteria Toxicosis",
      "Toad Toxicosis", "Bee and Wasp Sting Toxicosis",
      "Snake Envenomation", "Spider Envenomation",
      "Scorpion Envenomation",
      "Salt Toxicosis", "Water Intoxication",
      "Fluoride Toxicosis",
      "Aflatoxicosis", "Mycotoxicosis",
      "5-Fluorouracil Toxicosis", "Phenobarbital Toxicosis",
      "Benzodiazepine Toxicosis",
      "Sympathomimetic Toxicosis", "Amphetamine Toxicosis",
      "SSRI Toxicosis", "Tricyclic Antidepressant Toxicosis",
    ],
    // ═══ IMMUNOLOGY ═══
    immunology: [
      "Immune-Mediated Hemolytic Anemia Immunology",
      "Immune-Mediated Thrombocytopenia Immunology",
      "Systemic Lupus Erythematosus Immunology",
      "Pemphigus Complex",
      "Discoid Lupus Erythematosus Immunology",
      "Rheumatoid Arthritis Immunology",
      "Immune-Mediated Polyarthritis Immunology",
      "Vasculitis Immunology", "Polyarteritis Nodosa",
      "Anaphylaxis", "Angioedema", "Urticaria",
      "Drug Hypersensitivity", "Vaccine Reactions",
      "Serum Sickness", "Type I Hypersensitivity",
      "Type II Hypersensitivity", "Type III Hypersensitivity",
      "Type IV Hypersensitivity",
      "Immunodeficiency Syndromes",
      "Combined Immunodeficiency",
      "Selective IgA Deficiency",
      "Complement Deficiency",
      "Cyclic Hematopoiesis",
    ],
    // ═══ REPRODUCTIVE ═══
    reproductive: [
      "Pyometra", "Cystic Endometrial Hyperplasia",
      "Vaginitis", "Metritis",
      "Dystocia", "Uterine Inertia",
      "Eclampsia", "Pregnancy Toxemia",
      "Mastitis", "Agalactia",
      "Cryptorchidism", "Testicular Tumor",
      "Prostatic Disease", "Benign Prostatic Hyperplasia",
      "Prostatitis", "Prostatic Abscess",
      "Prostatic Cyst", "Prostatic Carcinoma",
      "Mammary Hyperplasia", "Mammary Fibroepithelial Hyperplasia",
      "False Pregnancy", "Pseudopregnancy",
      "Ovarian Remnant Syndrome", "Ovarian Cyst",
      "Infertility Female", "Infertility Male",
      "Breeding Management", "Artificial Insemination Complications",
      "Neonatal Mortality", "Fading Puppy Syndrome",
      "Fading Kitten Syndrome",
      "Canine Transmissible Venereal Tumor",
      "Phimosis", "Paraphimosis",
      "Uterine Prolapse", "Vaginal Prolapse",
      "Penile Prolapse", "Priapism",
      "Subinvolution of Placental Sites",
      "Perineal Hernia",
    ],
    // ═══ EMERGENCY / CRITICAL CARE ═══
    emergency: [
      "Gastric Dilatation Volvulus Emergency",
      "Heatstroke", "Hypothermia",
      "Drowning", "Smoke Inhalation",
      "Electric Shock", "Lightning Strike",
      "Burn Injury", "Chemical Burns",
      "Traumatic Brain Injury", "Spinal Cord Trauma",
      "Thoracic Trauma", "Abdominal Trauma",
      "Hemorrhagic Shock", "Hypovolemic Shock",
      "Distributive Shock", "Cardiogenic Shock",
      "Obstructive Shock", "Septic Shock",
      "Systemic Inflammatory Response Syndrome",
      "Multiple Organ Dysfunction Syndrome",
      "Cardiac Arrest", "Cardiopulmonary Resuscitation",
      "Airway Obstruction", "Choking",
      "Flail Chest", "Rib Fracture",
      "Urethral Obstruction Emergency",
      "Splenic Torsion", "Mesenteric Volvulus",
      "Acute Abdomen", "Hemoabdomen",
      "Uroabdomen", "Pneumoperitoneum",
      "High Rise Syndrome", "Vehicular Trauma",
      "Dog Bite Wound", "Cat Bite Wound",
      "Gunshot Wound", "Penetrating Wound",
      "Degloving Injury", "Wound Management",
      "Massive Transfusion", "Transfusion Medicine",
      "Acute Pain Management", "Triage and Stabilization",
      "Oxygen Therapy", "Mechanical Ventilation",
    ],
    // ═══ METABOLIC / NUTRITIONAL ═══
    metabolic: [
      "Obesity", "Cachexia",
      "Protein-Calorie Malnutrition",
      "Hypokalemia", "Hyperkalemia",
      "Hyponatremia", "Hypernatremia",
      "Hypocalcemia", "Hypercalcemia",
      "Hypomagnesemia", "Hypermagnesemia",
      "Hypophosphatemia", "Hyperphosphatemia",
      "Metabolic Acidosis", "Metabolic Alkalosis",
      "Respiratory Acidosis", "Respiratory Alkalosis",
      "Dehydration", "Fluid Overload",
      "Lactic Acidosis",
      "Hepatic Lipidosis Metabolic",
      "Feline Hepatic Lipidosis",
      "Taurine Deficiency", "Thiamine Deficiency",
      "Vitamin A Deficiency", "Vitamin A Toxicosis",
      "Vitamin D Deficiency", "Vitamin D Toxicosis",
      "Vitamin E Deficiency", "Vitamin K Deficiency",
      "Biotin Deficiency", "Zinc Deficiency",
      "Iron Deficiency", "Copper Deficiency",
      "Iodine Deficiency", "Selenium Deficiency",
      "Guinea Pig Scurvy", "Vitamin C Deficiency",
      "Diabetes Mellitus Metabolic",
      "Hyperlipidemia", "Hyperlipoproteinemia",
      "Amyloidosis", "Lysosomal Storage Disease",
      "Mucopolysaccharidosis Metabolic",
      "Glycogen Storage Disease Metabolic",
    ],
    // ═══ BEHAVIORAL ═══
    behavioral: [
      "Separation Anxiety", "Noise Phobia",
      "Storm Phobia", "Generalized Anxiety Disorder",
      "Compulsive Disorder", "Cognitive Dysfunction Syndrome Behavioral",
      "Aggression Dog", "Fear Aggression",
      "Territorial Aggression", "Redirected Aggression",
      "Predatory Behavior", "Resource Guarding",
      "Inter-Dog Aggression", "Inter-Cat Aggression",
      "Feline Aggression", "Pica",
      "Coprophagia", "Excessive Vocalization",
      "House Soiling", "Urine Marking",
      "Inappropriate Elimination", "Feline House Soiling",
      "Psychogenic Alopecia", "Acral Lick Dermatitis Behavioral",
      "Tail Chasing", "Fly Biting",
      "Canine Dysfunctional Behavior", "Feline Hyperesthesia Syndrome",
    ],
    // ═══ EXOTIC - RABBIT ═══
    rabbit: [
      "Rabbit GI Stasis", "Rabbit Dental Disease",
      "Rabbit Uterine Adenocarcinoma", "Rabbit VHD",
      "Rabbit Myxomatosis", "Rabbit Pasteurellosis",
      "Rabbit Encephalitozoonosis", "Rabbit Coccidiosis",
      "Rabbit Syphilis", "Rabbit Pododermatitis",
      "Rabbit Head Tilt", "Rabbit Ear Mites",
      "Rabbit Flystrike", "Rabbit Myiasis",
      "Rabbit Spinal Fracture", "Rabbit Obesity",
      "Rabbit Urolithiasis", "Rabbit Thymoma",
      "Rabbit Dental Abscess", "Rabbit Cheek Teeth Malocclusion",
      "Rabbit Phacoclastic Uveitis", "Rabbit Otitis",
      "Rabbit Respiratory Infection", "Rabbit Dermatophytosis",
      "Rabbit Pododermatitis Bumblefoot", "Rabbit Hepatic Coccidiosis",
      "Rabbit Intestinal Coccidiosis", "Rabbit Cecal Dysbiosis",
      "Rabbit Heat Stress", "Rabbit Pregnancy Toxemia",
      "Rabbit Tyzzer Disease", "Rabbit Mucoid Enteropathy",
      "Rabbit Hairball Obstruction", "Rabbit Pinworm",
      "Rabbit Red Urine", "Rabbit Hypovitaminosis D",
      "Rabbit Atherosclerosis", "Rabbit Lymphoma",
      "Rabbit Mammary Gland Tumor", "Rabbit Cutaneous Mass",
      "Rabbit Abscess", "Rabbit Mandibular Abscess",
      "Rabbit Corneal Ulcer", "Rabbit Glaucoma",
      "Rabbit Dacryocystitis", "Rabbit Gastric Dilation",
      "Rabbit Megacolon", "Rabbit Congenital Defects",
      "Rabbit Seizure", "Rabbit Posterior Paralysis",
      "Rabbit Antibiotic Toxicity",
      "Rabbit Ovarian Cyst", "Rabbit Orchitis",
      "Rabbit Fur Mites", "Rabbit Treponematosis",
      "Rabbit Viral Hemorrhagic Disease",
      "Rabbit Calicivirus", "Rabbit Herpesvirus",
    ],
    // ═══ EXOTIC - GUINEA PIG ═══
    guinea_pig: [
      "Guinea Pig Scurvy", "Guinea Pig Bumblefoot",
      "Guinea Pig Dental Disease", "Guinea Pig Malocclusion",
      "Guinea Pig Ovarian Cyst", "Guinea Pig Pneumonia",
      "Guinea Pig Pregnancy Toxemia", "Guinea Pig Urolithiasis",
      "Guinea Pig Barbering", "Guinea Pig Dermatophytosis",
      "Guinea Pig Sarcoptic Mange", "Guinea Pig Cervical Lymphadenitis",
      "Guinea Pig GI Stasis", "Guinea Pig Antibiotic Toxicity",
      "Guinea Pig Pododermatitis", "Guinea Pig Cystitis",
      "Guinea Pig Dystocia", "Guinea Pig Bloat",
      "Guinea Pig Heatstroke", "Guinea Pig Diabetes",
      "Guinea Pig Trichofolliculoma", "Guinea Pig Lymphoma",
      "Guinea Pig Mammary Tumor", "Guinea Pig Sebaceous Cyst",
      "Guinea Pig Lice Infestation", "Guinea Pig Bordetella",
      "Guinea Pig Streptococcal Infection",
      "Guinea Pig Vitamin C Deficiency Detailed",
      "Guinea Pig Adipocyte Lipoma",
      "Guinea Pig Conjunctivitis", "Guinea Pig Corneal Ulcer",
      "Guinea Pig Heart Disease", "Guinea Pig Renal Disease",
      "Guinea Pig Cecal Impaction",
      "Guinea Pig Alopecia", "Guinea Pig Satin Syndrome",
    ],
    // ═══ EXOTIC - HAMSTER ═══
    hamster: [
      "Hamster Wet Tail", "Hamster Cheek Pouch Impaction",
      "Hamster Diabetes", "Hamster Hibernation",
      "Hamster Demodicosis", "Hamster Lymphoma",
      "Hamster Dental Overgrowth", "Hamster Amyloidosis",
      "Hamster Congestive Heart Failure",
      "Hamster Skin Tumor", "Hamster Adrenal Tumor",
      "Hamster Polycystic Disease", "Hamster Pyometra",
      "Hamster Cushing Disease",
      "Hamster Bar Rub Alopecia", "Hamster Cage Paralysis",
      "Hamster Intussusception",
      "Hamster Atrial Thrombosis", "Hamster Pododermatitis",
      "Hamster Campylobacteriosis",
      "Hamster Respiratory Infection",
      "Hamster Tyzzer Disease",
      "Hamster Dermatophytosis",
      "Hamster Eye Proptosis",
    ],
    // ═══ EXOTIC - FERRET ═══
    ferret: [
      "Ferret Adrenal Disease", "Ferret Insulinoma",
      "Ferret Lymphoma", "Ferret Aplastic Anemia",
      "Ferret Distemper", "Ferret Influenza",
      "Ferret Epizootic Catarrhal Enteritis",
      "Ferret GI Foreign Body", "Ferret Helicobacter Gastritis",
      "Ferret Cardiomyopathy", "Ferret Heartworm",
      "Ferret Splenomegaly", "Ferret Hyperestrogenism",
      "Ferret Dental Disease", "Ferret Skin Tumor",
      "Ferret Mast Cell Tumor", "Ferret Chordoma",
      "Ferret Aleutian Disease", "Ferret Proliferative Bowel Disease",
      "Ferret Megaesophagus", "Ferret Renal Cyst",
      "Ferret Urolithiasis",
      "Ferret Coronavirus",
      "Ferret Systemic Coronavirus",
      "Ferret Ear Mites", "Ferret Dermatophytosis",
      "Ferret Seasonal Alopecia",
      "Ferret Pneumonia", "Ferret Cryptosporidiosis",
    ],
    // ═══ EXOTIC - CHINCHILLA ═══
    chinchilla: [
      "Chinchilla Dental Disease", "Chinchilla GI Stasis",
      "Chinchilla Fur Ring", "Chinchilla Heatstroke",
      "Chinchilla Dermatophytosis", "Chinchilla Fur Slip",
      "Chinchilla Malocclusion", "Chinchilla Bloat",
      "Chinchilla Constipation", "Chinchilla Diarrhea",
      "Chinchilla Pneumonia", "Chinchilla Otitis Media",
      "Chinchilla Conjunctivitis", "Chinchilla Diabetes",
      "Chinchilla Cardiomyopathy", "Chinchilla Listeriosis",
      "Chinchilla Penile Paraphimosis", "Chinchilla Rectal Prolapse",
      "Chinchilla Seizure", "Chinchilla Vitamin Deficiency",
    ],
    // ═══ EXOTIC - RAT ═══
    rat: [
      "Rat Mycoplasma Respiratory Disease",
      "Rat Mammary Tumor", "Rat Pituitary Adenoma",
      "Rat Tail Degloving", "Rat Ulcerative Dermatitis",
      "Rat Ringtail", "Rat Bumblefoot",
      "Rat Chromodacryorrhea", "Rat Sialodacryoadenitis",
      "Rat Pneumonia", "Rat Barbering",
      "Rat Renal Disease", "Rat Heart Failure",
      "Rat Zymbal Gland Tumor", "Rat Fibrosarcoma",
      "Rat Malocclusion", "Rat Mites",
      "Rat Seizure", "Rat Stroke",
      "Rat Hind Limb Paralysis",
    ],
    // ═══ EXOTIC - BIRD / AVIAN ═══
    avian: [
      "Avian Psittacosis", "Avian Aspergillosis",
      "Avian Proventricular Dilatation Disease",
      "Avian Polyomavirus", "Avian Bornavirus",
      "Psittacine Beak and Feather Disease",
      "Avian Pox", "Avian Candidiasis",
      "Avian Megabacteriosis", "Avian Gout",
      "Avian Egg Binding", "Avian Egg Peritonitis",
      "Avian Crop Stasis", "Avian Crop Burn",
      "Avian Feather Picking", "Avian Self Mutilation",
      "Avian Heavy Metal Toxicosis", "Avian Teflon Toxicosis",
      "Avian Bumblefoot", "Avian Liver Disease",
      "Avian Renal Disease", "Avian Atherosclerosis",
      "Avian Conure Bleeding Syndrome",
      "Avian Cloacal Prolapse", "Avian Obesity",
      "Avian Hypovitaminosis A",
    ],
    // ═══ BREED-SPECIFIC ═══
    breed_specific: [
      "Cavalier King Charles Spaniel Mitral Valve Disease",
      "Cavalier King Charles Spaniel Syringomyelia",
      "Boxer Cardiomyopathy", "Boxer Mast Cell Tumor",
      "Doberman Dilated Cardiomyopathy",
      "German Shepherd Degenerative Myelopathy",
      "German Shepherd Perianal Fistula",
      "Golden Retriever Hemangiosarcoma",
      "Golden Retriever Lymphoma Breed",
      "Labrador Retriever Obesity", "Labrador Exercise Induced Collapse",
      "Dalmatian Hyperuricosuria", "Dalmatian Deafness",
      "Shar-Pei Amyloidosis Breed", "Shar-Pei Fever Breed",
      "Scottish Fold Osteochondrodysplasia Breed",
      "Bulldog Brachycephalic Syndrome",
      "French Bulldog Hemivertebra",
      "French Bulldog IVDD",
      "Cocker Spaniel Immune Mediated Hemolytic Anemia",
      "Cocker Spaniel Ear Disease",
      "West Highland White Terrier Pulmonary Fibrosis",
      "Westie Atopic Dermatitis",
      "Miniature Schnauzer Hyperlipidemia",
      "Miniature Schnauzer Pancreatitis",
      "Bernese Mountain Dog Histiocytic Sarcoma",
      "Great Dane GDV Predisposition",
      "Great Dane Wobbler Syndrome",
      "Rottweiler Osteosarcoma",
      "Irish Setter Gluten Sensitive Enteropathy",
      "English Springer Spaniel Rage Syndrome",
      "Shiba Inu Glaucoma",
      "Persian Cat PKD",
      "Persian Cat Brachycephalic Syndrome",
      "Siamese Cat Amyloidosis",
      "Siamese Cat Megaesophagus",
      "Maine Coon Hypertrophic Cardiomyopathy",
      "Ragdoll Hypertrophic Cardiomyopathy",
      "Bengal Cat PK Deficiency",
      "Abyssinian Cat Renal Amyloidosis",
      "Burmese Cat Diabetes",
      "Burmese Cat Hypokalemic Polymyopathy",
    ],
    // ═══ CONGENITAL / GENETIC ═══
    congenital: [
      "Patent Ductus Arteriosus Congenital",
      "Persistent Right Aortic Arch Congenital",
      "Cleft Palate", "Pectus Excavatum",
      "Portosystemic Shunt Congenital",
      "Ectopic Ureter Congenital",
      "Hydrocephalus Congenital", "Cerebellar Hypoplasia Congenital",
      "Spina Bifida", "Meningomyelocele",
      "Agenesis of Corpus Callosum",
      "Microphthalmia", "Anophthalmia",
      "Cryptorchidism Congenital", "Hermaphroditism",
      "Diaphragmatic Hernia Congenital",
      "Umbilical Hernia", "Inguinal Hernia",
      "Imperforate Anus", "Rectovaginal Fistula",
      "Renal Agenesis", "Polydactyly",
      "Syndactyly", "Chondrodysplasia",
      "Achondroplasia", "Osteogenesis Imperfecta",
      "Hemimelia", "Phocomelia",
      "Dermoid Cyst", "Branchial Cyst",
      "Thyroglossal Duct Cyst",
      "Collie Eye Anomaly Congenital",
      "Retinal Dysplasia",
      "Congenital Deafness Breed",
      "Congenital Megaesophagus",
      "Congenital Hypothyroidism Breed",
      "Glycogen Storage Disease Congenital",
      "Lysosomal Storage Disease Congenital",
      "Pyruvate Kinase Deficiency",
      "Phosphofructokinase Deficiency",
      "Copper Storage Disease",
      "Von Willebrand Disease Congenital",
      "Factor VII Deficiency Congenital",
      "Cystinuria",
    ],
    // ═══ SURGERY (General / Soft Tissue) ═══
    surgery: [
      "Splenectomy Indications", "Splenic Torsion",
      "Liver Lobectomy", "Cholecystectomy",
      "Gastropexy", "Intestinal Resection Anastomosis",
      "Colectomy", "Subtotal Colectomy",
      "Cystotomy", "Urethrostomy",
      "Perineal Urethrostomy", "Scrotal Urethrostomy",
      "Nephrectomy", "Adrenalectomy",
      "Thyroidectomy", "Parathyroidectomy",
      "Total Ear Canal Ablation Surgery",
      "Lateral Wall Resection",
      "Salivary Gland Excision",
      "Laryngeal Tieback", "Arytenoid Lateralization",
      "Soft Palate Resection", "Nares Widening",
      "Lung Lobectomy", "Thoracotomy",
      "Pericardiectomy", "Patent Ductus Arteriosus Ligation",
      "Diaphragmatic Hernia Repair",
      "Perineal Hernia Repair",
      "Abdominal Wall Hernia Repair",
      "Wound Closure Techniques", "Skin Flap Surgery",
      "Skin Graft", "Negative Pressure Wound Therapy",
      "Limb Amputation", "Tail Amputation",
      "Digit Amputation",
      "Femoral Head Ostectomy", "Triple Pelvic Osteotomy",
      "Tibial Plateau Leveling Osteotomy",
      "Tibial Tuberosity Advancement",
      "Extracapsular Suture Repair",
    ],
    // ═══ PAIN / REHABILITATION ═══
    pain_rehab: [
      "Chronic Pain Syndrome", "Neuropathic Pain",
      "Cancer Pain", "Postoperative Pain Management",
      "Osteoarthritis Pain", "Multimodal Analgesia",
      "Physical Rehabilitation", "Hydrotherapy",
      "Acupuncture in Veterinary Medicine",
      "Laser Therapy", "Therapeutic Ultrasound",
      "Electroacupuncture", "TENS Therapy",
      "Range of Motion Exercises",
      "Weight Management Program",
      "Geriatric Wellness", "Palliative Care",
      "Hospice Care",
    ],
  };
}

// ─── Main ─────────────────────────────────────────────
async function main() {
  console.log("=== VetPro Disease Master List Builder ===\n");

  // 1. Extract from Merck sections
  console.log("1. Extracting Merck Manual section titles...");
  const merckDiseases = extractMerckDiseases();
  console.log(`   Found ${merckDiseases.length} Merck sections with content\n`);

  // 2. Load curated taxonomy
  console.log("2. Loading curated veterinary disease taxonomy...");
  const curated = getCuratedDiseases();
  let curatedTotal = 0;
  const curatedFlat: string[] = [];
  for (const [category, diseases] of Object.entries(curated)) {
    console.log(`   ${category}: ${diseases.length} diseases`);
    curatedTotal += diseases.length;
    curatedFlat.push(...diseases);
  }
  console.log(`   Total curated: ${curatedTotal}\n`);

  // 3. Combine all sources
  const allCandidates = {
    merckSections: merckDiseases,
    curatedByCategory: curated,
    curatedFlat: [...new Set(curatedFlat)],
    totalMerck: merckDiseases.length,
    totalCurated: curatedTotal,
    totalUniqueCurated: new Set(curatedFlat).size,
    generatedAt: new Date().toISOString(),
  };

  // 4. Write output
  fs.writeFileSync(OUTPUT_FILE, JSON.stringify(allCandidates, null, 2), "utf-8");
  console.log(`Output written to: ${OUTPUT_FILE}`);
  console.log(`Total unique curated diseases: ${allCandidates.totalUniqueCurated}`);
  console.log(`Total Merck sections: ${allCandidates.totalMerck}`);
}

main().catch(err => {
  console.error("Fatal error:", err);
  process.exit(1);
});
